---
title: "TEST"
author: "Unterweger L., Pirich G., Tijani S."
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(vars)
library(ggplot2)
library(stats)
library(urca)
library(forecast)
library(tidyverse)
library(quantmod)
library(lubridate)
library(gridExtra)
library(stargazer)
```

```{r}
ts_transform <- function(x) {
  output <- data.frame(matrix(NA,    # Create empty data frame
                                 nrow = NROW(x),
                                 ncol = 0))
  output$raw <- x
  output$log <- log(x)
  output$mom <- ((x-lag(x))/lag(x))*100
  output$yoy <- ((x-lag(x, 12))/lag(x, 12))*100
  output$yoy_1stlag <- lag((x-lag(x, 12))/lag(x, 12))*100
  return(output)
}
```

```{r}
fred <- read.csv("FRED_MD_data.csv")[,c("sasdate","S.P.500","CPIAUCSL")][-1,]
str(fred)

# Extract SP500 Growth and Inflation
ret <- ts_transform(fred$S.P.500)$mom
inf <- ts_transform(fred$CPIAUCSL)$mom

# Compute deflated stock returns
stockret <- ret - inf
head(stockret, n=10)

# Create time series
stockret_ts <- ts(stockret, frequency=12, start=c(1959,1))
head(stockret_ts)
plot(stockret_ts)
stockret_ts <- window(stockret_ts, start=c(1973,1), end=c(2006,12))
plot(stockret_ts)
```
```{r}
data <- read.table("data_kilian_park_2009.txt")
#("Global Oil Production Change","Global Real Activity", "Real Price of Oil", "US Stock Returns")
colnames(data) <- c("GOPC","GRA","RPO","USSR")
head(data)
```

```{r}
data$adj_stock_returns <- stockret_ts[-1]

df_2 <- data[,c("GOPC", "GRA", "RPO", "adj_stock_returns")]

var_rep <- VAR(df_2, p = 24, type = "const")
```


### Figure 1 
```{r}
# Supply Shock
irf_supply_specific_shocks <- irf(var_rep, impulse = "GOPC", response = "RPO", boot = TRUE, cumulative = FALSE, n.ahead = 15)

# Inverting Signs
for(x in 1:length(irf_supply_specific_shocks$irf$GOPC)){
  irf_supply_specific_shocks$irf$GOPC[x,] <- irf_supply_specific_shocks$irf$GOPC[x,]*(-1)
  irf_supply_specific_shocks$Upper$GOPC[x,] <- irf_supply_specific_shocks$Upper$GOPC[x,]*(-1)
  irf_supply_specific_shocks$Lower$GOPC[x,] <- irf_supply_specific_shocks$Lower$GOPC[x,]*(-1)
}

# Aggregate-demand shock
irf_agg_demand_shocks <- irf(var_rep, impulse = "GRA", response = "RPO", boot = TRUE, cumulative = FALSE, n.ahead = 15)


# Oil specific-demand shock
irf_oi_specific_demand_shocks <- irf(var_rep, impulse = "RPO", response = "RPO", boot = TRUE, cumulative = FALSE, n.ahead = 15)

```

```{r, figures-side, fig.show="hold", out.width="33%", fig.height=20}
# Figure 1
plot(irf_supply_specific_shocks, ylim=c(-6,12),mar=c(0.01, 0.01, 0.01, 0.01))

plot(irf_agg_demand_shocks, ylim=c(-6,12),mar=c(0.01, 0.01, 0.01, 0.01))

plot(irf_oi_specific_demand_shocks, ylim=c(-6,12),mar=c(0.01, 0.01, 0.01, 0.01))
```