% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Advanced Macroeconometrics - Assignment 1},
  pdfauthor={Unterweger L., Pirich G., Tijani S.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Advanced Macroeconometrics - Assignment 1}
\author{Unterweger L., Pirich G., Tijani S.}
\date{2023-04-14}

\begin{document}
\maketitle

\hypertarget{excercise-1}{%
\subsection{Excercise 1}\label{excercise-1}}

\hypertarget{loading-and-cleaning-data}{%
\subsubsection{Loading and Cleaning
Data}\label{loading-and-cleaning-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fredmd }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"FRED\_MD\_data.csv"}\NormalTok{)[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,]}
\FunctionTok{head}\NormalTok{(fredmd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    sasdate      RPI W875RX1 DPCERA3M086SBEA CMRMTSPLx  RETAILx  INDPRO IPFPNSS
## 2 1/1/1959 2442.158  2293.2          17.272  292266.4 18235.77 22.0151 23.3984
## 3 2/1/1959 2451.778  2301.5          17.452  294424.7 18369.56 22.4463 23.7142
## 4 3/1/1959 2467.594  2318.5          17.617  293418.7 18523.06 22.7696 23.8577
## 5 4/1/1959 2483.671  2334.9          17.553  299322.8 18534.47 23.2547 24.2022
## 6 5/1/1959 2498.026  2350.4          17.765  301364.3 18679.66 23.6050 24.4032
## 7 6/1/1959 2505.788  2357.4          17.831  301348.8 18849.75 23.6319 24.5755
##   IPFINAL IPCONGD IPDCONGD IPNCONGD IPBUSEQ   IPMAT  IPDMAT  IPNMAT IPMANSICS
## 2 22.2848 31.5847  18.6861  38.1504  8.1482 20.1315 12.1386 30.6520   20.8962
## 3 22.4778 31.8164  18.7842  38.5150  8.2572 20.7690 12.6977 31.1886   21.2804
## 4 22.5882 31.8164  19.1520  38.3327  8.3464 21.3085 13.1980 31.6572   21.6133
## 5 22.9191 32.3184  19.2746  38.9708  8.5645 21.8970 13.5953 32.6376   22.0742
## 6 23.1398 32.4728  19.6670  38.9708  8.8420 22.4610 14.0661 32.9308   22.3815
## 7 23.3052 32.3184  19.8141  38.6974  9.0502 22.3138 13.9631 32.8320   22.4071
##   IPB51222S IPFUELS  CUMFNS  HWI HWIURATIO CLF16OV CE16OV UNRATE UEMPMEAN
## 2   19.9176 34.6702 80.1973 1357 0.3335792   67936  63868    6.0     16.3
## 3   19.8634 34.1979 81.4428 1421 0.3583859   67649  63684    5.9     15.5
## 4   19.9989 35.0637 82.4769 1524 0.4009471   68068  64267    5.6     15.3
## 5   20.0802 34.9063 83.9922 1589 0.4449734   68339  64768    5.2     14.9
## 6   20.3783 34.2373 84.9159 1655 0.4757114   68178  64699    5.1     14.7
## 7   20.4867 34.2373 84.7686 1717 0.5007291   68278  64849    5.0     14.9
##   UEMPLT5 UEMP5TO14 UEMP15OV UEMP15T26 UEMP27OV CLAIMSx PAYEMS USGOOD
## 2    1574      1169     1396       594      802  291078  52478  18796
## 3    1554      1164     1277       545      732  282958  52688  18890
## 4    1459      1093     1210       530      680  260346  53014  19069
## 5    1494       934     1039       408      631  246413  53321  19269
## 6    1479      1005      965       390      575  246952  53550  19378
## 7    1522       963      963       415      548  258258  53681  19462
##   CES1021000001 USCONS MANEMP DMANEMP NDMANEMP SRVPRD USTPU USWTRADE USTRADE
## 2         713.0   2993  14998    8740     6258  33682 10774   2568.7  5350.3
## 3         704.2   2980  15115    8839     6276  33798 10816   2575.4  5381.3
## 4         704.1   3013  15259    8965     6294  33945 10873   2584.4  5431.6
## 5         705.2   3085  15385    9077     6308  34052 10905   2596.9  5395.4
## 6         710.0   3087  15487    9160     6327  34172 10949   2607.4  5456.3
## 7         715.0   3100  15554    9209     6345  34219 10968   2614.8  5467.8
##   USFIRE USGOVT CES0600000007 AWOTMAN AWHMAN HOUST HOUSTNE HOUSTMW HOUSTS
## 2   2418   8105          39.8     2.5   40.2  1657     350     452    505
## 3   2420   8116          39.7     2.6   40.3  1667     346     469    508
## 4   2430   8132          40.0     2.8   40.4  1620     330     413    503
## 5   2439   8142          40.2     2.9   40.5  1590     275     391    536
## 6   2447   8153          40.3     2.9   40.7  1498     260     355    487
## 7   2454   8143          40.2     2.9   40.6  1503     254     343    518
##   HOUSTW PERMIT PERMITNE PERMITMW PERMITS PERMITW ACOGNO  AMDMNOx ANDENOx
## 2    350     NA       NA       NA      NA      NA     NA 14716.48      NA
## 3    344     NA       NA       NA      NA      NA     NA 15400.25      NA
## 4    374     NA       NA       NA      NA      NA     NA 15745.42      NA
## 5    388     NA       NA       NA      NA      NA     NA 15919.42      NA
## 6    396     NA       NA       NA      NA      NA     NA 15248.82      NA
## 7    388     NA       NA       NA      NA      NA     NA 15961.75      NA
##    AMDMUOx  BUSINVx ISRATIOx  M1SL  M2SL M2REAL BOGMBASE TOTRESNS NONBORRES
## 2 42620.35 84889.56 1.560000 138.9 286.6  987.9    50500     18.9     18300
## 3 43677.15 85181.81 1.539338 139.4 287.7  992.1    49800     18.6     18100
## 4 44781.65 85620.19 1.529007 139.7 289.2  998.3    49700     18.4     17800
## 5 45522.75 86769.72 1.529007 139.7 290.1 1001.0    50100     18.7     18000
## 6 45384.45 87266.54 1.518675 140.7 292.2 1006.2    50100     18.6     17800
## 7 45731.63 88143.30 1.529007 141.2 294.1 1010.3    50300     18.5     17500
##   BUSLOANS  REALLN NONREVSL    CONSPI S.P.500 S.P..indust S.P.div.yield
## 2  35.2130 24.9242 48.96116 0.1249647   55.62       59.30      3.158342
## 3  35.2201 25.2270 49.51371 0.1257651   54.77       58.33      3.219518
## 4  35.1304 25.4218 50.00773 0.1261229   56.16       59.79      3.151709
## 5  35.5581 25.7261 50.46343 0.1261901   57.10       60.92      3.111506
## 6  36.3064 26.0187 51.00724 0.1267576   57.96       62.09      3.076829
## 7  37.1404 26.2668 51.67544 0.1276567   57.46       61.75      3.115211
##   S.P.PE.ratio FEDFUNDS CP3Mx TB3MS TB6MS  GS1  GS5 GS10  AAA  BAA COMPAPFFx
## 2     18.44574     2.48  3.30  2.82  3.09 3.36 4.01 4.02 4.12 4.87      0.82
## 3     18.41812     2.43  3.26  2.70  3.13 3.54 3.96 3.96 4.14 4.89      0.83
## 4     18.99935     2.80  3.35  2.80  3.13 3.61 3.99 3.99 4.13 4.85      0.55
## 5     19.27297     2.96  3.42  2.95  3.27 3.72 4.12 4.12 4.23 4.86      0.46
## 6     19.49414     2.90  3.56  2.84  3.33 3.96 4.35 4.31 4.37 4.96      0.66
## 7     19.10270     3.39  3.83  3.21  3.52 4.07 4.50 4.34 4.46 5.04      0.44
##   TB3SMFFM TB6SMFFM T1YFFM T5YFFM T10YFFM AAAFFM BAAFFM TWEXAFEGSMTHx EXSZUSx
## 2     0.34     0.61   0.88   1.53    1.54   1.64   2.39            NA  4.3122
## 3     0.27     0.70   1.11   1.53    1.53   1.71   2.46            NA  4.3133
## 4     0.00     0.33   0.81   1.19    1.19   1.33   2.05            NA  4.3228
## 5    -0.01     0.31   0.76   1.16    1.16   1.27   1.90            NA  4.3226
## 6    -0.06     0.43   1.06   1.45    1.41   1.47   2.06            NA  4.3228
## 7    -0.18     0.13   0.68   1.11    0.95   1.07   1.65            NA  4.3115
##    EXJPUSx EXUSUKx EXCAUSx WPSFD49207 WPSFD49502 WPSID61 WPSID62 OILPRICEx
## 2 359.8417  2.8065  0.9671       33.1       33.4    30.6    31.6      3.00
## 3 359.8417  2.8093  0.9748       33.2       33.4    30.7    31.4      3.00
## 4 359.8417  2.8127  0.9698       33.2       33.3    30.7    31.5      2.97
## 5 359.8417  2.8165  0.9636       33.2       33.4    30.7    31.7      2.97
## 6 359.8417  2.8145  0.9630       33.3       33.3    30.9    31.5      2.97
## 7 359.8417  2.8125  0.9590       33.2       33.4    30.9    31.3      2.97
##   PPICMM CPIAUCSL CPIAPPSL CPITRNSL CPIMEDSL CUSR0000SAC CUSR0000SAD
## 2   32.5    29.01     44.8     29.3     21.1        33.3        38.1
## 3   32.5    29.00     44.7     29.4     21.2        33.3        38.1
## 4   32.9    28.97     44.7     29.6     21.3        33.2        38.3
## 5   32.7    28.98     44.8     29.7     21.3        33.2        38.3
## 6   32.9    29.04     44.9     29.7     21.4        33.3        38.4
## 7   33.0    29.11     45.0     29.8     21.5        33.3        38.4
##   CUSR0000SAS CPIULFSL CUSR0000SA0L2 CUSR0000SA0L5  PCEPI DDURRG3M086SBEA
## 2        22.9     28.9          30.7          29.6 16.042          56.918
## 3        23.0     28.9          30.7          29.6 16.057          56.951
## 4        23.0     28.9          30.7          29.6 16.068          57.022
## 5        23.1     29.0          30.7          29.6 16.100          57.080
## 6        23.2     29.1          30.7          29.6 16.109          57.175
## 7        23.2     29.2          30.8          29.7 16.155          57.289
##   DNDGRG3M086SBEA DSERRG3M086SBEA CES0600000008 CES2000000008 CES3000000008
## 2          17.791          11.326          2.13          2.45          2.04
## 3          17.798          11.343          2.14          2.46          2.05
## 4          17.785          11.363          2.15          2.45          2.07
## 5          17.796          11.403          2.16          2.47          2.08
## 6          17.777          11.421          2.17          2.48          2.08
## 7          17.817          11.463          2.17          2.50          2.09
##   UMCSENTx DTCOLNVHFNM DTCTHFNM  INVEST VIXCLSx
## 2       NA        6476    12298 84.2043      NA
## 3       NA        6476    12298 83.5280      NA
## 4       NA        6508    12349 81.6405      NA
## 5       NA        6620    12484 81.8099      NA
## 6     95.3        6753    12646 80.7315      NA
## 7       NA        6956    12926 78.6972      NA
\end{verbatim}

\textit{Create a function that takes a vector containing observations of a time series as input and returns a dataframe with the following transformed series in its columns as output:
– the original time series in its raw form.
– the log-transformed time series.
– month-on-month growth rates in percent.
– year-on-year growth rates in percent.
– the first lag of the year-on-year growth rates of the time series.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{input\_function }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(input\_vector)\{}
\NormalTok{  output\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
    \AttributeTok{orig =}\NormalTok{ input\_vector,}
    \AttributeTok{log\_ts =} \FunctionTok{log}\NormalTok{(input\_vector),}
    \AttributeTok{mom\_growth =}\NormalTok{ ((input\_vector}\SpecialCharTok{{-}}\FunctionTok{lag}\NormalTok{(input\_vector))}\SpecialCharTok{/}\FunctionTok{lag}\NormalTok{(input\_vector))}\SpecialCharTok{*}\DecValTok{100}\NormalTok{,}
    \AttributeTok{yoy\_growth =}\NormalTok{ ((input\_vector}\SpecialCharTok{{-}}\FunctionTok{lag}\NormalTok{(input\_vector,}\AttributeTok{n=}\DecValTok{12}\NormalTok{))}\SpecialCharTok{/}\FunctionTok{lag}\NormalTok{(input\_vector,}\AttributeTok{n=}\DecValTok{12}\NormalTok{))}\SpecialCharTok{*}\DecValTok{100}\NormalTok{,}
    \AttributeTok{yoy\_growth\_lag =}\NormalTok{ ((}\FunctionTok{lag}\NormalTok{(input\_vector,}\AttributeTok{n=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{{-}}\FunctionTok{lag}\NormalTok{(input\_vector,}\AttributeTok{n=}\DecValTok{13}\NormalTok{))}\SpecialCharTok{/}\FunctionTok{lag}\NormalTok{(input\_vector,}\AttributeTok{n=}\DecValTok{1}\NormalTok{))}\SpecialCharTok{*}\DecValTok{100}
\NormalTok{  )}
  \FunctionTok{return}\NormalTok{(output\_df)}
\NormalTok{\}}
\FunctionTok{input\_function}\NormalTok{(fredmd}\SpecialCharTok{$}\NormalTok{RETAILx)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          orig    log_ts    mom_growth   yoy_growth yoy_growth_lag
## 1    18235.77  9.811141            NA           NA             NA
## 2    18369.56  9.818450   0.733663186           NA             NA
## 3    18523.06  9.826772   0.835591676           NA             NA
## 4    18534.47  9.827387   0.061590156           NA             NA
## 5    18679.66  9.835191   0.783392087           NA             NA
## 6    18849.75  9.844255   0.910554677           NA             NA
## 7    18843.53  9.843925  -0.033012371           NA             NA
## 8    18963.84  9.850289   0.638450090           NA             NA
## 9    18715.96  9.837132  -1.307082289           NA             NA
## 10   18852.86  9.844420   0.731463994           NA             NA
## 11   18356.08  9.817716  -2.635053349           NA             NA
## 12   18271.04  9.813072  -0.463302992           NA             NA
## 13   18763.67  9.839678   2.696259288   2.89484160             NA
## 14   18833.16  9.843374   0.370329405   2.52371272     2.81339818
## 15   18812.42  9.842272  -0.110138193   1.56215008     2.46158928
## 16   19306.09  9.868176   2.624179909   4.16316936     1.53812230
## 17   19017.77  9.853129  -1.493419287   1.81000498     3.99677678
## 18   18991.84  9.851765  -0.136336358   0.75378265     1.77782623
## 19   18801.01  9.841666  -1.004805577  -0.22565911     0.74814327
## 20   18865.31  9.845080   0.342012368  -0.51955153    -0.22616948
## 21   18847.68  9.844145  -0.093457945   0.70375706    -0.52226497
## 22   19013.62  9.852911   0.880426976   0.85267907     0.69883893
## 23   18741.89  9.838516  -1.429116866   2.10181368     0.84546992
## 24   18604.99  9.831185  -0.730452117   1.82777997     2.05854686
## 25   18619.51  9.831965   0.078042233  -0.76829541     1.79497184
## 26   18553.13  9.828394  -0.356486336  -1.48686598    -0.77424389
## 27   18749.15  9.838904   1.056515127  -0.33629201    -1.50930736
## 28   18417.27  9.821044  -1.770107304  -4.60381413    -0.33742675
## 29   18694.18  9.835968   1.503547689  -1.70147789    -4.82599391
## 30   18833.16  9.843374   0.743411936  -0.83551770    -1.73092927
## 31   18818.64  9.842603  -0.077096735   0.09377758    -0.84255742
## 32   19026.06  9.853565   1.102232034   0.85211655     0.09368972
## 33   19059.25  9.855308   0.174434455   1.12254444     0.84491687
## 34   19402.54  9.873159   1.801164499   2.04549178     1.11008326
## 35   19539.44  9.880190   0.705580460   4.25543686     2.00449010
## 36   19546.70  9.880562   0.037155005   5.06159763     4.08174095
## 37   19714.71  9.889121   0.859553263   5.88202533     4.81774287
## 38   19716.79  9.889226   0.010521329   6.27201072     5.55526333
## 39   20048.67  9.905918   1.683236012   6.93107648     5.90184629
## 40   20157.57  9.911335   0.543168978   9.44926230     6.48181680
## 41   20294.47  9.918104   0.679152100   8.56033289     8.63346367
## 42   20034.15  9.905194  -1.282706425   6.37700318     7.88532299
## 43   20351.51  9.920910   1.584096870   8.14549461     5.99471971
## 44   20478.04  9.927108   0.621719436   7.63150721     7.53197776
## 45   20539.23  9.930092   0.298809816   7.76514118     7.09040263
## 46   20861.78  9.945674   1.570389800   7.52084665     7.20561501
## 47   20970.67  9.950880   0.521998532   7.32484079     6.99477998
## 48   20966.52  9.950682  -0.019782388   7.26375552     6.82492584
## 49   21054.68  9.954878   0.420459045   6.79678047     6.77186388
## 50   20896.00  9.947313  -0.753657461   5.98074798     6.36421851
## 51   21062.98  9.955272   0.799086752   5.05923128     5.64324002
## 52   21154.24  9.959596   0.433305454   4.94443306     4.81559899
## 53   21020.46  9.953251  -0.632445986   3.57726901     4.71147722
## 54   21177.06  9.960674   0.745016783   5.70481956     3.45372015
## 55   21422.86  9.972214   1.160683663   5.26423074     5.39693420
## 56   21395.89  9.970954  -0.125871383   4.48214738     5.00096824
## 57   21343.00  9.968479  -0.247212799   3.91335085     4.28986913
## 58   21714.29  9.985726   1.739637482   4.08650263     3.76597504
## 59   21469.53  9.974390  -1.127191108   2.37883282     3.92606393
## 60   21941.42  9.996132   2.197961472   4.64978235     2.32355923
## 61   21827.34  9.990919  -0.519947053   3.66976997     4.44318397
## 62   21927.94  9.995517   0.460895169   4.93845543     3.53986506
## 63   22086.62 10.002727   0.723643764   4.85991433     4.70604928
## 64   22269.15 10.010958   0.826446279   5.27038288     4.63467319
## 65   22569.92 10.024373   1.350596111   7.37122559     5.00652010
## 66   22587.55 10.025154   0.078117821   6.66046329     6.86517784
## 67   22699.56 10.030101   0.495890532   5.95952751     6.24454750
## 68   23019.00 10.044075   1.407228042   7.58603973     5.62434323
## 69   23235.75 10.053448   0.941653548   8.86826377     7.05113763
## 70   22337.60 10.014027  -3.865381188   2.87051632     8.14586681
## 71   22547.10 10.023362   0.937877249   5.01908124     2.79041695
## 72   23595.64 10.068817   4.650413960   7.53923236     4.77920886
## 73   23768.84 10.076131   0.734033657   8.89480183     7.01068084
## 74   23919.22 10.082438   0.632690476   9.08101972     8.16825200
## 75   23681.72 10.072459  -0.992932400   7.22201352     8.32502276
## 76   23880.85 10.080832   0.840851341   7.23733231     6.73556976
## 77   24251.10 10.096217   1.550421274   7.44876390     6.74889253
## 78   24105.90 10.090212  -0.598725569   6.72207172     6.93238678
## 79   24498.97 10.106386   1.630598444   7.92707999     6.29867057
## 80   24576.76 10.109556   0.317500649   6.76728993     7.34484801
## 81   24642.10 10.112212   0.265856425   6.05249059     6.33835506
## 82   25277.85 10.137684   2.579966368  13.16278207     5.70707067
## 83   25582.77 10.149674   1.206252803  13.46366143    11.63172363
## 84   25674.04 10.153236   0.356751915   8.80840401    11.86605585
## 85   25844.13 10.159839   0.662492437   8.73112838     8.09533426
## 86   25920.87 10.162804   0.296962153   8.36838224     8.03001726
## 87   26374.10 10.180138   1.748489576  11.36901110     7.72216219
## 88   26015.25 10.166438  -1.360597722   8.93772257    10.20841524
## 89   25568.25 10.149107  -1.718226725   5.43129626     8.20443311
## 90   26158.37 10.171925   2.308035501   8.51439142     5.15150288
## 91   26268.31 10.176119   0.420268019   7.22208112     7.84632463
## 92   26565.96 10.187386   1.133133302   8.09385154     6.73562856
## 93   26619.89 10.189414   0.203006070   8.02609431     7.48780012
## 94   26505.81 10.185119  -0.428565894   4.85783445     7.42977367
## 95   26515.15 10.185471   0.035215410   3.64454533     4.63278159
## 96   26326.39 10.178327  -0.711882961   2.54090085     3.51638894
## 97   25052.80 10.128741  -4.837693027  -3.06192061     2.47793888
## 98   24799.74 10.118588  -1.010101010  -4.32521104    -3.15863552
## 99   25049.69 10.128617   1.007862145  -5.02162799    -4.52074270
## 100  25112.95 10.131139   0.252556608  -3.46834636    -5.28712789
## 101  24998.87 10.126586  -0.454282640  -2.22690953    -3.59296275
## 102  25747.67 10.156100   2.995353480  -1.57005787    -2.27763030
## 103  25569.29 10.149147  -0.692822044  -2.66108653    -1.59510190
## 104  25575.51 10.149391   0.024336815  -3.72828421    -2.73383628
## 105  26301.50 10.177381   2.838605026  -1.19608839    -3.87266829
## 106  25901.17 10.162043  -1.522082016  -2.28117540    -1.21056785
## 107  26509.96 10.185276   2.350444488  -0.01955720    -2.33442780
## 108  27271.21 10.213587   2.871562143   3.58887490    -0.01956103
## 109  26779.61 10.195396  -1.802624088   6.89269746     3.46453700
## 110  27095.94 10.207139   1.181209084   9.25894946     6.44823980
## 111  27749.32 10.230967   2.411390949  10.77712913     8.47431676
## 112  27686.06 10.228684  -0.227986237  10.24613861     9.72865899
## 113  27863.41 10.235070   0.640569417  11.45867909     9.29387527
## 114  28319.74 10.251314   1.637757738   9.98952710    10.28065215
## 115  28675.48 10.263798   1.256134171  12.14813011     9.08225298
## 116  29051.95 10.276841   1.312886545  13.59286293    10.83221815
## 117  28433.83 10.255335  -2.127659572   8.10725552    11.96630015
## 118  29231.38 10.282998   2.804931443  12.85737168     7.49927050
## 119  29954.25 10.307427   2.472946586  12.99244940    11.39258472
## 120  29523.85 10.292954  -1.436881089   8.26012549    11.49851116
## 121  29842.24 10.303680   1.078441694  11.43642771     7.62988723
## 122  30059.00 10.310917   0.726350194  10.93546661    10.26273719
## 123  29817.35 10.302846  -0.803919533   7.45253404     9.85750269
## 124  29988.48 10.308569   0.573913036   8.31616409     6.93565220
## 125  30275.76 10.318103   0.957980272   8.65778304     7.67767596
## 126  30084.93 10.311780  -0.630309665   6.23306234     7.96793640
## 127  30102.56 10.312366   0.058604523   4.97667187     5.86734694
## 128  30455.18 10.324012   1.171403970   4.83007285     4.74074076
## 129  30874.18 10.337676   1.375787483   8.58257952     4.60752599
## 130  31212.29 10.348567   1.095098950   6.77665426     7.90419564
## 131  31186.36 10.347736  -0.083070303   4.11328855     6.34656920
## 132  31472.60 10.356873   0.917858333   6.60062527     3.95078151
## 133  31569.06 10.359933   0.306465427   5.78647389     6.19191985
## 134  31716.33 10.364587   0.466506814   5.51357693     5.46995630
## 135  31419.71 10.355191  -0.935221241   5.37391302     5.22546680
## 136  31792.04 10.366971   1.185014035   6.01417948     5.09985144
## 137  32246.30 10.381159   1.428851061   6.50863252     5.67299536
## 138  32451.65 10.387507   0.636819740   7.86679535     6.11089671
## 139  32723.38 10.395845   0.837328235   8.70628768     7.29306486
## 140  32713.01 10.395528  -0.031693703   7.41358761     8.00900101
## 141  32814.64 10.398630   0.310696824   6.28506164     6.90190857
## 142  33085.33 10.406845   0.824905184   6.00099682     5.91340075
## 143  32353.12 10.384466  -2.213096761   3.74127038     5.66126451
## 144  33301.06 10.413344   2.929956717   5.80966190     3.60634718
## 145  34098.61 10.437012   2.394967157   8.01274682     5.49067240
## 146  34447.08 10.447179   1.021959984   8.60992119     7.41833446
## 147  34494.79 10.448563   0.138495806   9.78709360     7.92738002
## 148  35135.73 10.466974   1.858087801  10.51738763     8.91461216
## 149  34929.34 10.461083  -0.587401876   8.32046827     9.51650040
## 150  35584.81 10.479674   1.876540303   9.65484183     7.68134444
## 151  35693.70 10.482730   0.306024293   9.07707910     8.80475652
## 152  35892.83 10.488293   0.557880070   9.72037284     8.32171083
## 153  36512.00 10.505396   1.725034657  11.26738307     8.85922330
## 154  36952.77 10.517396   1.207214893  11.68928876    10.12640251
## 155  37381.11 10.528921   1.159135551  15.54095208    10.46589954
## 156  37357.25 10.528282  -0.063812664  12.18038557    13.45060067
## 157  37073.08 10.520646  -0.760688510   8.72315834    10.85785676
## 158  37382.14 10.528948   0.833659722   8.52050340     8.02327533
## 159  38347.71 10.554450   2.582954162  11.16957306     7.85151481
## 160  38442.09 10.556908   0.246112235   9.41023672    10.04732928
## 161  38949.24 10.570015   1.319268345  11.50865527     8.60087411
## 162  39203.34 10.576517   0.652376501  10.16875053    10.32086276
## 163  39412.84 10.581847   0.534391540  10.41957230     9.23015872
## 164  39788.27 10.591328   0.952581433  10.85298195     9.43634546
## 165  40539.15 10.610024   1.887185910  11.02968329     9.79042851
## 166  41110.61 10.624021   1.409639780  11.25175413     9.93399509
## 167  41387.52 10.630735   0.673579047  10.71775379    10.11377683
## 168  42323.01 10.653086   2.260311736  13.29261521     9.68024858
## 169  43049.00 10.670094   1.715349930  16.11928607    11.73299352
## 170  43675.42 10.684541   1.455141193  16.83497947    13.88166136
## 171  44007.30 10.692111   0.759878415  14.75862069    14.40919453
## 172  43684.75 10.684754  -0.732937396  13.63783523    12.86057692
## 173  43684.75 10.684754   0.000000000  12.15816802    12.00113958
## 174  44086.12 10.693900   0.918781592  12.45502645    10.84019848
## 175  44099.60 10.694206   0.030582481  11.89147939    11.07556225
## 176  44231.32 10.697188   0.298675945  11.16671880    10.62768984
## 177  44825.59 10.710535   1.343556558  10.57357757    10.04501970
## 178  45074.50 10.716072   0.555285628   9.64201923     9.56248120
## 179  45433.35 10.724002   0.796116060   9.77547238     8.79409126
## 180  44253.10 10.697681  -2.597758357   4.56038032     8.90496954
## 181  44807.96 10.710141   1.253837684   4.08595934     4.36148023
## 182  45074.50 10.716072   0.594852331   3.20336246     3.92556246
## 183  45723.74 10.730373   1.440371829   3.90035822     3.10393226
## 184  46334.61 10.743644   1.335994729   6.06585787     3.75394107
## 185  46864.58 10.755017   1.143790846   7.27902944     5.71895423
## 186  46978.66 10.757449   0.243432864   6.56111792     6.78513730
## 187  47734.73 10.773414   1.609378096   8.24298582     6.15714066
## 188  49092.33 10.801458   2.844044670  10.98996436     7.61526094
## 189  47918.30 10.777253  -2.391465080   6.89942390     9.90176402
## 190  47469.22 10.767837  -0.937168584   5.31280919     6.45412636
## 191  47221.35 10.762601  -0.522176111   3.93544410     5.04478917
## 192  46500.55 10.747219  -1.526432531   5.07862852     3.78643121
## 193  48207.66 10.783273   3.671157101   7.58726044     4.83316978
## 194  48908.75 10.797712   1.454326398   8.50647706     7.05219225
## 195  47802.14 10.774826  -2.262606555   4.54555764     7.83960303
## 196  48463.83 10.788573   1.384218192   4.59530846     4.34792041
## 197  50705.06 10.833781   4.624537215   8.19483480     4.39341738
## 198  50649.05 10.832676  -0.110452024   7.81287944     7.57414605
## 199  51440.38 10.848179   1.562372013   7.76300352     7.24670325
## 200  51995.24 10.858907   1.078650782   5.91317208     7.20377427
## 201  52096.88 10.860860   0.195476128   8.72021297     5.58303746
## 202  52442.24 10.867468   0.662924031  10.47629451     8.02078356
## 203  52660.04 10.871612   0.415307030  11.51742770     9.48284386
## 204  53482.48 10.887109   1.561792216  15.01472031    10.32791729
## 205  54816.22 10.911741   2.493794603  13.70853234    13.05460751
## 206  54430.41 10.904678  -0.703825639  11.28970695    12.05585197
## 207  54791.33 10.911287   0.663084486  14.62107570    10.14443048
## 208  55867.86 10.930745   1.964792736  15.27745083    12.75600985
## 209  55416.72 10.922637  -0.807529517   9.29228882    13.25276602
## 210  56564.81 10.943142   2.071753406  11.67990825     8.50223645
## 211  56985.89 10.950559   0.744407780  10.78045929    10.45837916
## 212  56678.90 10.945157  -0.538710743   9.00785893     9.73137262
## 213  56684.08 10.945249   0.009149137   8.80514412     8.26349496
## 214  57535.56 10.960159   1.502149848   9.71225155     8.09258073
## 215  57775.14 10.964314   0.416396277   9.71344165     8.85247674
## 216  59421.06 10.992404   2.848834078  11.10378529     8.85346545
## 217  58999.98 10.985292  -0.708625691   7.63234569     9.99406569
## 218  60358.62 11.008059   2.302770363  10.89135323     7.09112641
## 219  60857.47 11.016290   0.826488878  11.07136096     9.82164336
## 220  61801.26 11.031679   1.550810339  10.62040543     9.96779086
## 221  61530.57 11.027289  -0.438000302  11.03250799     9.60076523
## 222  61857.26 11.032585   0.530946610   9.35643565     9.93628640
## 223  62566.66 11.043988   1.146823607   9.79325156     8.55590765
## 224  62512.73 11.043125  -0.086196902  10.29277219     8.91972086
## 225  62786.53 11.047496   0.437992541  10.76571220     9.33222729
## 226  64035.23 11.067189   1.988800599  11.29677698     9.71935447
## 227  64542.38 11.075077   0.791992622  11.71307018    10.15013847
## 228  64837.96 11.079647   0.457963738   9.11613781    10.48495951
## 229  63558.15 11.059710  -1.973863103   7.72570666     8.35452756
## 230  65058.87 11.083048   2.361176835   7.78720918     7.17164630
## 231  66663.30 11.107410   2.466124663   9.54003989     7.22461342
## 232  68327.89 11.132073   2.497005142  10.56067395     8.70918058
## 233  68766.59 11.138473   0.642057016  11.76004585     9.55192617
## 234  69956.17 11.155624   1.729884618  13.09290276    10.52258503
## 235  69505.03 11.149154  -0.644903043  11.08956187    11.57712150
## 236  70422.88 11.162274   1.320560457  12.65367067     9.98254173
## 237  70750.61 11.166916   0.465376571  12.68438526    11.23236429
## 238  72009.68 11.184556   1.779588967  12.45323357    11.25655984
## 239  73112.15 11.199750   1.530994354  13.27773492    11.07414449
## 240  74080.82 11.212912   1.324916664  14.25532256    11.72139867
## 241  73624.49 11.206733  -0.615996309  15.83799748    12.47672515
## 242  74245.73 11.215135   0.843792705  14.12083533    13.67254081
## 243  75742.30 11.235092   2.015700957  13.61917949    12.37358216
## 244  75568.06 11.232789  -0.230039301  10.59621748    11.98669058
## 245  76350.05 11.243084   1.034818774  11.02782596     9.58099447
## 246  76676.75 11.247354   0.427890290   9.60683153     9.93248842
## 247  76346.94 11.243043  -0.430124978   9.84377099     8.76481091
## 248  79172.07 11.279379   3.700383078  12.42378722     8.96161057
## 249  79954.06 11.289208   0.987712546  13.00829694    11.05085279
## 250  79380.53 11.282008  -0.717324750  10.23591429    11.51092202
## 251  80439.44 11.295260   1.333960455  10.02198737     9.28546232
## 252  80669.68 11.298118   0.286230023   8.89414664     9.10907684
## 253  82378.86 11.319084   2.118742122  11.89057460     8.16769947
## 254  81694.36 11.310740  -0.830920308  10.03240767    10.62696715
## 255  80465.37 11.295582  -1.504379834   6.23570813     9.11768440
## 256  79398.16 11.282231  -1.326287298   5.06841608     5.86969131
## 257  79445.87 11.282831   0.060086730   4.05476996     4.82391975
## 258  80539.00 11.296497   1.375943184   5.03706109     3.89676510
## 259  82222.26 11.317181   2.089986607   7.69554704     4.79550840
## 260  83039.51 11.327072   0.993958052   4.88485421     7.14565017
## 261  83307.09 11.330289   0.322230127   4.19369065     4.65734948
## 262  85248.59 11.353327   2.330532217   7.39230980     4.02489885
## 263  85946.57 11.361481   0.818764677   6.84631254     6.88346290
## 264  86051.32 11.362699   0.121877635   6.67120927     6.40762641
## 265  88078.90 11.385988   2.356244958   6.91930002     6.25399236
## 266  89224.93 11.398916   1.301132749   9.21797639     6.47151638
## 267  89767.34 11.404977   0.607920395  11.56022426     8.43998094
## 268  89188.63 11.398509  -0.644684243  12.33084277    10.36231716
## 269  88533.16 11.391132  -0.734917902  11.43834364    10.97725475
## 270  89344.19 11.400252   0.916077041  10.93283198    10.26428002
## 271  90040.11 11.408010   0.778910214   9.50819258     9.85536183
## 272  91468.23 11.423747   1.586094889  10.15024916     8.68263128
## 273  91089.68 11.419600  -0.413860354   9.34204793     9.21491257
## 274  89858.61 11.405993  -1.351489821   5.40773994     8.54387503
## 275  89715.49 11.404399  -0.159276102   4.38518161     5.13030632
## 276  90099.22 11.408667   0.427725879   4.70405322     4.20096180
## 277  89123.29 11.397776  -1.083177931   1.18573817     4.49271358
## 278  91478.60 11.423860   2.642756570   2.52583371     1.17184318
## 279  90645.79 11.414715  -0.910389557   0.97857985     2.46360709
## 280  91064.79 11.419326   0.462237279   2.10358622     0.96909647
## 281  92065.61 11.430257   1.099026249   3.98997236     2.06024715
## 282  90593.93 11.414143  -1.598513009   1.39878810     3.83688183
## 283  92199.40 11.431709   1.772160589   2.39814783     1.37949193
## 284  91748.25 11.426804  -0.489319340   0.30614328     2.34198360
## 285  92999.02 11.440344   1.363266418   2.09611860     0.30520890
## 286  94079.71 11.451898   1.162038587   4.69749083     2.05308354
## 287  95538.94 11.467289   1.551062695   6.49102931     4.48672723
## 288  95555.54 11.467463   0.017368844   6.05589705     6.09537663
## 289  94918.74 11.460776  -0.666413419   6.50274050     5.71009932
## 290  95181.14 11.463537   0.276439290   4.04743549     6.10570251
## 291  97716.91 11.489830   2.664153250   7.80082608     3.88999063
## 292  97986.56 11.492586   0.275952829   7.60093388     7.23633238
## 293  99628.33 11.509202   1.675504611   8.21448687     7.06400364
## 294 101926.60 11.532008   2.306843461  12.50930151     7.59093086
## 295 102523.98 11.537852   0.586092547  11.19810122    11.11845984
## 296 100997.33 11.522849  -1.489064660  10.08093690    10.07040686
## 297 102925.35 11.541759   1.908977010  10.67358092     9.15774991
## 298 104521.49 11.557148   1.550770331  11.09886233     9.64419948
## 299 105882.19 11.570082   1.301845627  10.82621395     9.99007739
## 300 106548.03 11.576351   0.628844539  11.50377162     9.76864007
## 301 108965.57 11.598787   2.268966510  14.79878940    10.31693498
## 302 108836.96 11.597606  -0.118022236  14.34720071    12.89106747
## 303 108071.57 11.590549  -0.703252247  10.59658884    12.54705023
## 304 110077.37 11.608939   1.855992625  12.33925003     9.58129807
## 305 110796.09 11.615447   0.652929682  11.20942726    10.98391704
## 306 112380.82 11.629649   1.430309803  10.25661899    10.07956567
## 307 110614.60 11.613807  -1.571642093   7.89143589     9.30249729
## 308 110001.66 11.608251  -0.554123157   8.91540527     7.31423753
## 309 111562.53 11.622341   1.418954633   8.39169296     8.18562374
## 310 112102.87 11.627172   0.484340307   7.25342335     7.74200746
## 311 114242.46 11.646078   1.908594629   7.89581942     6.76288283
## 312 113760.20 11.641848  -0.422140063   6.76893731     7.31800311
## 313 114618.94 11.649368   0.754868321   5.18821678     6.33980021
## 314 115847.93 11.660034   1.072242964   6.44171493     4.93231746
## 315 116437.02 11.665106   0.508500317   7.74066000     6.05187067
## 316 117941.89 11.677947   1.292431578   7.14453956     7.18452996
## 317 118681.36 11.684198   0.626978519   7.11691467     6.66813221
## 318 118019.67 11.678607  -0.557531454   5.01762677     6.64406242
## 319 118226.06 11.680354   0.174875846   6.88106504     4.77789008
## 320 119921.76 11.694595   1.434286063   9.01814002     6.43805808
## 321 123301.75 11.722390   2.818497081  10.52254830     8.27214629
## 322 119725.74 11.692959  -2.900208609   6.79988893     9.52072537
## 323 120303.42 11.697772   0.482501745   5.30534804     6.36694382
## 324 121807.25 11.710195   1.250032357   7.07369995     5.03806135
## 325 122987.50 11.719838   0.968947633   7.30120522     6.60638415
## 326 121841.48 11.710476  -0.931821023   5.17363315     6.80440188
## 327 120996.22 11.703515  -0.693735097   3.91559561     4.91913515
## 328 121767.84 11.709872   0.637723385   3.24393248     3.76805386
## 329 123536.14 11.724289   1.452188492   4.09060326     3.14200787
## 330 123666.82 11.725346   0.105781028   4.78492026     3.92984874
## 331 124088.93 11.728754   0.341328420   4.95903298     4.56642067
## 332 125358.37 11.738932   1.023009311   4.53346474     4.72473196
## 333 132724.03 11.796027   5.875685661   7.64164589     4.33685495
## 334 127169.19 11.753274  -4.185257801   6.21708248     7.09915371
## 335 126579.07 11.748622  -0.464046593   5.21651421     5.85318513
## 336 132296.74 11.792803   4.517075244   8.61154389     4.95788541
## 337 123758.09 11.726084  -6.454167037   0.62655480     7.92875562
## 338 129924.83 11.774711   4.982904301   6.63432075     0.62265354
## 339 130806.39 11.781474   0.678512705   8.10783012     6.22156235
## 340 131877.74 11.789631   0.819035219   8.30260032     7.49976215
## 341 131853.89 11.789450  -0.018087890   6.73304565     7.66611355
## 342 133676.12 11.803175   1.382006365   8.09376045     6.30830462
## 343 134557.67 11.809748   0.659471962   8.43648395     7.48772215
## 344 137070.63 11.828252   1.867566945   9.34301862     7.78011574
## 345 135263.95 11.814983  -1.318059345   1.91368497     8.54468693
## 346 134802.43 11.811566  -0.341200139   6.00243032     1.87775074
## 347 135312.70 11.815344   0.378528478   6.89974433     5.66254029
## 348 137001.14 11.827745   1.247806017   3.55594578     6.45440677
## 349 137463.70 11.831115   0.337630697  11.07451733     3.43384028
## 350 138391.92 11.837845   0.675252536   6.51691489     9.97034927
## 351 140775.24 11.854920   1.722148107   7.62107128     6.11819719
## 352 140139.48 11.850393  -0.451611952   6.26469637     7.08139325
## 353 141388.18 11.859264   0.891040055   7.23095320     5.89536938
## 354 142066.46 11.864050   0.479728861   6.27662136     6.74334507
## 355 142468.86 11.866879   0.283250954   5.87940590     5.90592858
## 356 143287.16 11.872606   0.574365430   4.53527438     5.55292680
## 357 142819.41 11.869336  -0.326437843   5.58571405     4.33851100
## 358 145827.08 11.890177   2.105920519   8.17837002     5.29021762
## 359 147042.59 11.898478   0.833528889   8.66872591     7.56007880
## 360 148095.27 11.905611   0.715902943   8.09783720     7.97720396
## 361 149179.06 11.912903   0.731823449   8.52251719     7.49121112
## 362 147182.60 11.899429  -1.338301800   6.35201372     7.85322476
## 363 148025.78 11.905142   0.572882128   5.15043910     5.97263136
## 364 150793.87 11.923669   1.870003580   7.60270274     4.89816224
## 365 151799.88 11.930318   0.667143507   7.36391173     7.06553140
## 366 151845.51 11.930619   0.030061618   6.88343637     6.85883330
## 367 152604.69 11.935606   0.499965909   7.11441451     6.44013385
## 368 154992.15 11.951130   1.564475126   8.16890807     6.64188340
## 369 154840.73 11.950152  -0.097695463   8.41714655     7.55199273
## 370 153129.47 11.939039  -1.105172255   5.00757427     7.76366730
## 371 154468.40 11.947745   0.874376932   5.05011324     4.76877435
## 372 154867.70 11.950326   0.258495066   4.57302126     4.80733726
## 373 159719.37 11.981174   3.132785091   7.06553856     4.37304116
## 374 158483.12 11.973403  -0.774015896   7.67788941     6.59926495
## 375 159089.83 11.977224   0.382828353   7.47440921     7.13042338
## 376 157927.22 11.969890  -0.730793084   4.73052902     6.95459437
## 377 157608.82 11.967871  -0.201610215   3.82670843     4.51685776
## 378 159003.75 11.976683   0.885060565   4.71415892     3.68566864
## 379 159547.21 11.980095   0.341786652   4.54934684     4.50193075
## 380 160334.38 11.985017   0.493382568   3.44677602     4.35138715
## 381 160864.35 11.988317   0.330541078   3.89020612     3.33193179
## 382 161452.40 11.991966   0.365556497   5.43522437     3.74453595
## 383 161003.33 11.989180  -0.278147173   4.23059103     5.15503656
## 384 159668.55 11.980855  -0.829038880   3.09997057     4.05887656
## 385 156101.88 11.958264  -2.233798651  -2.26490565     3.00676183
## 386 158656.32 11.974496   1.636392640   0.10928603    -2.31739240
## 387 159555.50 11.980147   0.566751850   0.29270833     0.10916672
## 388 161176.53 11.990255   1.015964209   2.05747533     0.29185405
## 389 161233.57 11.990609   0.035390947   2.29984136     2.01599669
## 390 161582.05 11.992768   0.216129989   1.62152991     2.24813776
## 391 162113.05 11.996049   0.328630696   1.60820617     1.59565587
## 392 161212.83 11.990481  -0.555306794   0.54788317     1.58275225
## 393 161366.32 11.991432   0.095212398   0.31204470     0.54489776
## 394 160322.98 11.984946  -0.646571154  -0.69954331     0.31107401
## 395 161163.05 11.990172   0.523986970   0.09920124    -0.70447139
## 396 161028.22 11.989335  -0.083658322   0.85155856     0.09910293
## 397 164095.00 12.008201   1.904498162   5.12045392     0.84436827
## 398 164213.00 12.008920   0.071909565   3.50234089     4.87103483
## 399 163721.00 12.005919  -0.299610871   2.61068865     3.38382771
## 400 164709.00 12.011936   0.603465652   2.19167804     2.54426579
## 401 165612.00 12.017403   0.548239623   2.71558129     2.14467370
## 402 166077.00 12.020207   0.280776755   2.78184039     2.64378710
## 403 167257.00 12.027287   0.710513798   3.17306120     2.70654853
## 404 167800.00 12.030528   0.324650089   4.08600931     3.07547451
## 405 169400.00 12.040018   0.953516091   4.97853358     3.92560858
## 406 170625.00 12.047223   0.723140496   6.42579436     4.74243011
## 407 171003.00 12.049436   0.221538462   6.10558896     6.03781667
## 408 173105.00 12.061654   1.229218201   7.49979070     5.75425764
## 409 175108.00 12.073158   1.157101181   6.71135623     6.97656307
## 410 173744.00 12.065338  -0.778947849   5.80404718     6.28926148
## 411 172306.00 12.057027  -0.827654480   5.24367674     5.48565706
## 412 176749.00 12.082486   2.578552111   7.30986163     4.98241501
## 413 178426.00 12.091929   0.948803105   7.73736203     6.81191973
## 414 178157.00 12.090420  -0.150762781   7.27373447     7.18168877
## 415 180743.00 12.104831   1.451528708   8.06304071     6.78053627
## 416 180707.00 12.104632  -0.019917784   7.69189511     7.46142313
## 417 181773.00 12.110514   0.589905206   7.30401417     7.14250140
## 418 182884.00 12.116607   0.611201884   7.18476190     6.80684150
## 419 184747.00 12.126743   1.018678507   8.03728590     6.70315610
## 420 186399.00 12.135645   0.894195846   7.67973195     7.43936302
## 421 185142.00 12.128878  -0.674359841   5.73017795     7.13201251
## 422 188074.00 12.144591   1.583649307   8.24776683     5.41962386
## 423 191579.00 12.163056   1.863628146  11.18533307     7.61934132
## 424 191639.00 12.163369   0.031318673   8.42437581    10.06007965
## 425 190929.00 12.159657  -0.370488262   7.00738682     7.76981721
## 426 193130.00 12.171119   1.152784543   8.40438490     6.54850756
## 427 193743.00 12.174288   0.317402786   7.19253304     7.75280899
## 428 196163.00 12.186701   1.249077386   8.55307210     6.70991984
## 429 197765.00 12.194835   0.816667771   8.79778625     7.87916172
## 430 199571.00 12.203925   0.913205067   9.12436298     8.08636513
## 431 199731.00 12.204727   0.080171969   8.11055119     8.36143528
## 432 200702.00 12.209576   0.486153877   7.67332443     7.50209031
## 433 201573.00 12.213907   0.433976742   8.87480961     7.12648603
## 434 198399.00 12.198035  -1.574615648   5.48986037     8.15138932
## 435 200247.00 12.207307   0.931456308   4.52450425     5.20415930
## 436 201032.00 12.211219   0.392015860   4.90140316     4.32865411
## 437 202986.00 12.220892   0.971984560   6.31491287     4.67239047
## 438 205500.00 12.233201   1.238509060   6.40501217     5.93981851
## 439 204920.00 12.230375  -0.282238443   5.76898262     6.01946472
## 440 206521.00 12.238157   0.781280500   5.28030261     5.45432364
## 441 207006.00 12.240503   0.234842946   4.67271762     5.01547058
## 442 206176.00 12.236485  -0.400954562   3.30959909     4.46412181
## 443 208664.00 12.248481   1.206735993   4.47251553     3.20357365
## 444 210399.00 12.256761   0.831480275   4.83154129     4.28104513
## 445 208699.00 12.248648  -0.807988631   3.53519569     4.60886221
## 446 212008.00 12.264379   1.585537065   6.85940957     3.41448689
## 447 213891.00 12.273222   0.888174031   6.81358522     6.41909739
## 448 214676.00 12.276885   0.367009365   6.78697919     6.37895003
## 449 216299.00 12.284417   0.756023030   6.55858039     6.35562429
## 450 216068.00 12.283348  -0.106796610   5.14257908     6.15490594
## 451 216332.00 12.284570   0.122183757   5.56900254     4.89105282
## 452 216358.00 12.284690   0.012018564   4.76319599     5.27522512
## 453 219256.00 12.297995   1.339446658   5.91770287     4.54663105
## 454 221060.00 12.306189   0.822782501   7.21907497     5.58707629
## 455 220963.00 12.305751  -0.043879490   5.89416478     6.73301366
## 456 221991.00 12.310392   0.465236261   5.50953189     5.56609025
## 457 223481.00 12.317082   0.671198382   7.08292804     5.22183332
## 458 225422.00 12.325729   0.868530211   6.32711973     6.61443255
## 459 226161.00 12.329002   0.327829582   5.73656676     5.95061706
## 460 224615.00 12.322143  -0.683583819   4.62976765     5.42533859
## 461 222929.00 12.314609  -0.750617724   3.06520141     4.42490484
## 462 226057.00 12.328542   1.403137322   4.62308162     2.97404106
## 463 228703.00 12.340179   1.170501245   5.71852523     4.41879703
## 464 229309.00 12.342826   0.264972475   5.98591224     5.40919883
## 465 230312.00 12.347190   0.437401061   5.04250739     5.64783763
## 466 229836.00 12.345121  -0.206676161   3.96996291     4.80044461
## 467 230440.00 12.347746   0.262796081   4.28895335     3.81837484
## 468 231181.00 12.350956   0.321558757   4.13980747     4.11256726
## 469 231587.00 12.352711   0.175619969   3.62715399     3.97524018
## 470 231684.00 12.353130   0.041884907   2.77790100     3.50019647
## 471 233083.00 12.359150   0.603839713   3.06065148     2.70281936
## 472 235986.00 12.371528   1.245479078   5.06244018     2.96975755
## 473 237075.00 12.376132   0.461468053   6.34551808     4.81850618
## 474 238971.00 12.384097   0.799746916   5.71271847     5.96688812
## 475 237411.00 12.377548  -0.652798875   3.80755827     5.40400300
## 476 236379.00 12.373192  -0.434689210   3.08317598     3.66790081
## 477 238550.00 12.382334   0.918440301   3.57688701     2.99095943
## 478 242549.00 12.398959   1.676378118   5.53133539     3.45336407
## 479 244291.00 12.406115   0.718205394   6.01067523     5.24141514
## 480 246530.00 12.415239   0.916529876   6.63938645     5.66987732
## 481 246868.00 12.416609   0.137102989   6.59838419     6.22601712
## 482 249520.00 12.427294   1.074258308   7.69841681     6.18994766
## 483 250667.00 12.431881   0.459682591   7.54409373     7.14812440
## 484 252477.00 12.439075   0.722073508   6.98812641     7.01488429
## 485 254735.00 12.447979   0.894338890   7.44911948     6.53168407
## 486 255449.00 12.450778   0.280291283   6.89539735     6.93269476
## 487 257456.00 12.458604   0.785675419   8.44316396     6.45060266
## 488 260230.00 12.469321   1.077465664  10.09015183     7.78579641
## 489 261317.00 12.473490   0.417707413   9.54391113     9.16535373
## 490 261818.00 12.475405   0.191721166   7.94437413     8.71240677
## 491 264965.00 12.487353   1.201980001   8.46285782     7.35969261
## 492 269863.00 12.505670   1.848546034   9.46456821     7.80253996
## 493 268044.00 12.498906  -0.674045719   8.57786347     8.64623902
## 494 272020.00 12.513631   1.483338556   9.01731324     7.90019549
## 495 275192.00 12.525224   1.166090729   9.78389656     8.27145063
## 496 271046.00 12.510044  -1.506584494   7.35472934     8.91195965
## 497 271394.00 12.511327   0.128391491   6.53973737     6.85086664
## 498 273422.00 12.518772   0.747253071   7.03584669     6.13830814
## 499 272630.00 12.515871  -0.289662134   5.89382263     6.57335547
## 500 272918.00 12.516927   0.105637677   4.87568689     5.56578513
## 501 277548.00 12.533749   1.696480261   6.21123004     4.64901546
## 502 276927.00 12.531509  -0.223745082   5.77080262     5.84799746
## 503 276029.00 12.528261  -0.324273184   4.17564584     5.45595049
## 504 275791.00 12.527399  -0.086222824   2.19667016     4.00827449
## 505 278834.00 12.538372   1.103371756   4.02545851     2.14945375
## 506 278773.00 12.538153  -0.021876816   2.48253805     3.86968591
## 507 276450.00 12.529785  -0.833294473   0.45713538     2.42240102
## 508 280808.00 12.545426   1.576415265   3.60160268     0.45505516
## 509 281496.00 12.547874   0.245007265   3.72226357     3.47639668
## 510 280401.00 12.543976  -0.388993094   2.55246469     3.58868332
## 511 279504.00 12.540772  -0.319899002   2.52136595     2.48893549
## 512 281413.00 12.547579   0.682995592   3.11265655     2.45935657
## 513 276084.00 12.528460  -1.893658075  -0.52747633     3.01869494
## 514 294540.00 12.593170   6.684921980   6.36015990    -0.53027340
## 515 287111.00 12.567624  -2.522238066   4.01479555     5.97983296
## 516 283705.00 12.555690  -1.186300769   2.86956427     3.85983122
## 517 283508.00 12.554996  -0.069438325   1.67626617     2.78951728
## 518 285054.00 12.560434   0.545310891   2.25308764     1.64863073
## 519 284262.00 12.557652  -0.277842093   2.82582746     2.20344215
## 520 288833.00 12.573604   1.608023584   2.85782456     2.74816894
## 521 284951.00 12.560073  -1.344029249   1.22737090     2.77842213
## 522 287372.00 12.568533   0.849619759   2.48608243     1.21248916
## 523 290385.00 12.578963   1.048466796   3.89296754     2.42577565
## 524 292650.00 12.586733   0.779998967   3.99306358     3.74709437
## 525 288410.00 12.572138  -1.448829660   4.46458324     3.83974030
## 526 289576.00 12.576173   0.404285566  -1.68533985     4.27377691
## 527 291484.00 12.582740   0.658894384   1.52310430    -1.71423046
## 528 293947.00 12.591155   0.844986346   3.61008794     1.50025387
## 529 295248.00 12.595571   0.442596795   4.14097662     3.48430159
## 530 291167.00 12.581652  -1.382227822   2.14450595     3.97631821
## 531 296325.00 12.599212   1.771491962   4.24362032     2.09948243
## 532 295600.00 12.596762  -0.244663798   2.34287633     4.07086813
## 533 296410.00 12.599499   0.274018945   4.02139315     2.28924222
## 534 299626.00 12.610290   1.084983638   4.26415935     3.86592895
## 535 302747.00 12.620653   1.041631901   4.25710694     4.08976524
## 536 307809.00 12.637235   1.672023174   5.17990774     4.08327746
## 537 305933.00 12.631121  -0.609468859   6.07572553     4.92480727
## 538 304809.00 12.627441  -0.367400705   5.26044976     5.72772470
## 539 308527.00 12.639565   1.219780256   5.84697616     4.99755585
## 540 307407.00 12.635928  -0.363015230   4.57905677     5.52398980
## 541 309254.00 12.641918   0.600832122   4.74380859     4.37856002
## 542 311393.00 12.648811   0.691664457   6.94652897     4.52896325
## 543 316912.00 12.666379   1.772358402   6.94743947     6.49532905
## 544 313512.00 12.655593  -1.072853032   6.05953992     6.49612511
## 545 318964.00 12.672834   1.739008395   7.60905503     5.71333793
## 546 314958.00 12.660195  -1.255941109   5.11704592     7.07101742
## 547 318549.00 12.671532   1.140152020   5.21953975     4.86795065
## 548 318977.00 12.672874   0.134359235   3.62822400     4.96061830
## 549 324569.00 12.690253   1.753104456   6.09152984     3.50119288
## 550 326740.00 12.696920   0.668887047   7.19499752     5.74176831
## 551 327836.00 12.700269   0.335434902   6.25844740     6.71206464
## 552 331874.00 12.712511   1.231713418   7.95915513     5.88983516
## 553 328696.00 12.702889  -0.957592339   6.28674164     7.37237626
## 554 333026.00 12.715976   1.317326648   6.94716965     5.91488792
## 555 333581.00 12.717641   0.166653655   5.25981976     6.49588921
## 556 336583.00 12.726600   0.899931351   7.35888897     4.99698724
## 557 334522.00 12.720458  -0.612330391   4.87766645     6.85447572
## 558 343998.00 12.748391   2.832698597   9.22027699     4.65081519
## 559 346576.00 12.755857   0.749422962   8.79833244     8.44190955
## 560 343307.00 12.746380  -0.943227459   7.62750919     8.08682655
## 561 343956.00 12.748269   0.189043626   5.97315209     7.08695133
## 562 344097.00 12.748679   0.040993615   5.31217482     5.63647676
## 563 347325.00 12.758016   0.938107569   5.94474066     5.04421718
## 564 347405.00 12.758247   0.023033182   4.67978811     5.61117109
## 565 357331.00 12.786418   2.857183978   8.71169713     4.47057469
## 566 354706.00 12.779045  -0.734613006   6.51000222     8.01357845
## 567 355665.00 12.781745   0.270364753   6.62028113     6.11210411
## 568 357423.00 12.786675   0.494285353   6.19163772     6.20921373
## 569 356704.00 12.784662  -0.201162208   6.63095402     5.83062646
## 570 357879.00 12.787950   0.329404773   4.03519788     6.21860142
## 571 359006.00 12.791094   0.314910906   3.58651493     3.87868525
## 572 360691.00 12.795777   0.469351487   5.06368935     3.46233768
## 573 358961.00 12.790969  -0.479634923   4.36247660     4.81963786
## 574 358462.00 12.789578  -0.139012316   4.17469493     4.18011985
## 575 359266.00 12.791818   0.224291557   3.43799035     4.00739827
## 576 363730.00 12.804167   1.242533388   4.69912638     3.32372114
## 577 363616.00 12.803854  -0.031341929   1.75887343     4.48821928
## 578 364006.00 12.804926   0.107256006   2.62188968     1.72847179
## 579 367158.00 12.813548   0.865919793   3.23141158     2.55490294
## 580 366187.00 12.810899  -0.264463800   2.45199665     3.13026000
## 581 370934.00 12.823779   1.296332202   3.98930205     2.39331271
## 582 368154.00 12.816257  -0.749459473   2.87108213     3.83626198
## 583 369614.00 12.820214   0.396573173   2.95482527     2.79095161
## 584 371358.00 12.824922   0.471843599   2.95737903     2.87002116
## 585 372869.00 12.828982   0.406885000   3.87451562     2.87243038
## 586 375289.00 12.835452   0.649021506   4.69422142     3.72999633
## 587 378860.00 12.844922   0.951533352   5.45389767     4.48374453
## 588 374298.00 12.832808  -1.204138732   2.90545185     5.17183128
## 589 375236.00 12.835310   0.250602461   3.19567896     2.82341877
## 590 371833.00 12.826200  -0.906895927   2.15023928     3.09671780
## 591 372745.00 12.828650   0.245271399   1.52168821     2.10497723
## 592 372572.00 12.828186  -0.046412427   1.74364464     1.49887993
## 593 376036.00 12.837440   0.929753175   1.37544684     1.71376271
## 594 376455.00 12.838554   0.111425502   2.25476295     1.35678499
## 595 375038.00 12.834783  -0.376406211   1.46747688     2.20504443
## 596 372284.00 12.827412  -0.734325588   0.24935507     1.44625345
## 597 366729.00 12.812378  -1.492140409  -1.64669093     0.24873484
## 598 352950.00 12.774082  -3.757270355  -5.95247929    -1.67426083
## 599 339350.00 12.734787  -3.853237002 -10.42865438    -6.32922510
## 600 332091.00 12.713164  -2.139089436 -11.27630925   -11.64284662
## 601 336929.00 12.727628   1.456829604 -10.20877528   -12.70946819
## 602 335576.00 12.723604  -0.401568283  -9.75088279   -11.36945766
## 603 329747.00 12.706081  -1.737013374 -11.53550014   -10.80440794
## 604 331352.00 12.710937   0.486736801 -11.06363334   -13.03969407
## 605 334256.00 12.719662   0.876409377 -11.11063834   -12.43994302
## 606 339883.00 12.736357   1.683440237  -9.71483976   -12.49940166
## 607 340517.00 12.738220   0.186534778  -9.20466726   -10.76017335
## 608 346668.00 12.756123   1.806370901  -6.88076845   -10.13781984
## 609 338507.00 12.732300  -2.354125561  -7.69560084    -7.38920235
## 610 341654.00 12.741554   0.929670583  -3.20045332    -8.33719834
## 611 344375.00 12.749486   0.796419770   1.48077206    -3.30626892
## 612 346072.00 12.754402   0.492776770   4.20999064     1.45916515
## 613 346043.00 12.754318  -0.008379759   2.70502094     4.03991077
## 614 346835.00 12.756604   0.228873290   3.35512671     2.63377673
## 615 354360.00 12.778069   2.169619560   7.46420741     3.24621218
## 616 357461.00 12.786782   0.875098770   7.87953596     6.94576137
## 617 354255.00 12.777772  -0.896881058   5.98313867     7.30401358
## 618 353766.00 12.776391  -0.138036160   4.08464089     5.64536845
## 619 354844.00 12.779434   0.304721200   4.20742577     3.92434547
## 620 356610.00 12.784398   0.497683489   2.86787359     4.03754889
## 621 359646.00 12.792875   0.851350215   6.24477485     2.78791958
## 622 363577.00 12.803746   1.093019247   6.41672569     5.87772421
## 623 367198.00 12.813656   0.995937587   6.62736842     6.02980937
## 624 369229.00 12.819172   0.553107588   6.69138214     6.21544780
## 625 372025.00 12.826716   0.757253629   7.50831544     6.27171755
## 626 375064.00 12.834852   0.816880586   8.13902864     6.98393925
## 627 378576.00 12.844172   0.936373526   6.83372841     7.52644882
## 628 380337.00 12.848813   0.465164194   6.39957925     6.39660200
## 629 380219.00 12.848503  -0.031025117   7.32918378     6.01466594
## 630 383327.00 12.856644   0.817423643   8.35608849     6.82869609
## 631 382954.00 12.855670  -0.097305955   7.92179098     7.71169263
## 632 383839.00 12.857978   0.231098252   7.63551218     7.34030719
## 633 387758.00 12.868137   1.021000993   7.81657519     7.09385967
## 634 390104.00 12.874169   0.605016531   7.29611609     7.24988266
## 635 391393.00 12.877467   0.330424707   6.58908818     6.79998154
## 636 391585.00 12.877958   0.049055553   6.05477901     6.18176615
## 637 395641.00 12.888263   1.035790441   6.34796049     5.70910530
## 638 400385.00 12.900182   1.199066831   6.75111448     5.96904770
## 639 401654.00 12.903346   0.316944940   6.09600186     6.32416299
## 640 400237.00 12.899812  -0.352791208   5.23220197     5.74574136
## 641 399367.00 12.897636  -0.217371208   5.03604502     4.97205406
## 642 395553.00 12.888040  -0.955011305   3.18944400     4.79458743
## 643 397650.00 12.893328   0.530143875   3.83753662     3.09086267
## 644 402287.00 12.904921   1.166100842   4.80618176     3.69571231
## 645 405455.00 12.912765   0.787497483   4.56392905     4.58578080
## 646 405572.00 12.913054   0.028856470   3.96509649     4.36472605
## 647 407386.00 12.917516   0.447269535   4.08617425     3.81387275
## 648 408981.00 12.921424   0.391520573   4.44245821     3.92576083
## 649 412420.00 12.929798   0.840870358   4.24096593     4.25349833
## 650 417383.00 12.941760   1.203384899   4.24541379     4.06842539
## 651 414116.00 12.933901  -0.782734323   3.10267046     4.07251853
## 652 412015.00 12.928815  -0.507345768   2.94275642     3.00930174
## 653 414466.00 12.934746   0.594881254   3.78073301     2.85863379
## 654 415550.00 12.937358   0.261541357   5.05545401     3.64300087
## 655 418500.00 12.944432   0.709902539   5.24330441     4.81217663
## 656 417575.00 12.942219  -0.221027479   3.80027195     4.98207885
## 657 417861.00 12.942904   0.068490690   3.05977235     3.66113872
## 658 419434.00 12.946661   0.376440970   3.41788881     2.96892986
## 659 420688.00 12.949647   0.298974332   3.26520794     3.30492998
## 660 422955.00 12.955021   0.538879169   3.41678464     3.16196326
## 661 419245.00 12.946211  -0.877161873   1.65486640     3.30389758
## 662 425006.00 12.959859   1.374136841   1.82638009     1.62792639
## 663 429468.00 12.970303   1.049867531   3.70717384     1.79362174
## 664 433648.00 12.979988   0.973297196   5.25053700     3.57465515
## 665 434471.00 12.981884   0.189785264   4.82669266     4.98860827
## 666 435577.00 12.984427   0.254562445   4.81939598     4.60445001
## 667 436347.00 12.986193   0.176777011   4.26451613     4.59780934
## 668 439596.00 12.993611   0.744590888   5.27354367     4.09009343
## 669 438665.00 12.991491  -0.211785367   4.97868909     5.00937224
## 670 440261.00 12.995123   0.363831170   4.96550113     4.74257121
## 671 441328.00 12.997544   0.242356239   4.90624881     4.73060298
## 672 438686.00 12.991539  -0.598647718   3.71930820     4.67679368
## 673 436395.00 12.986303  -0.522241421   4.09068683     3.58593618
## 674 435744.00 12.984810  -0.149176778   2.52655257     3.92992587
## 675 442131.00 12.999361   1.465768892   2.94853167     2.46429096
## 676 443119.00 13.001594   0.223463182   2.18402944     2.86408327
## 677 446198.00 13.008518   0.694847208   2.69914448     2.13734911
## 678 446744.00 13.009741   0.122367200   2.56372582     2.62820542
## 679 450243.00 13.017543   0.783222606   3.18462141     2.49964185
## 680 450183.00 13.017409  -0.013326137   2.40834766     3.08633338
## 681 448506.00 13.013677  -0.372515177   2.24339758     2.35171030
## 682 447191.00 13.010741  -0.293195632   1.57406629     2.19417355
## 683 449027.00 13.014838   0.410562824   1.74450749     1.54967341
## 684 450939.00 13.019087   0.425809584   2.79311398     1.71459623
## 685 447626.00 13.011713  -0.734689171   2.57358586     2.71721896
## 686 452393.00 13.022307   1.064951544   3.82082140     2.50901422
## 687 450886.00 13.018970  -0.333117444   1.98018234     3.68020725
## 688 452345.00 13.022200   0.323585119   2.08205922     1.94173250
## 689 454211.00 13.026317   0.412516995   1.79583952     2.03959367
## 690 459028.00 13.036866   1.060520331   2.74967319     1.76415807
## 691 457977.00 13.034574  -0.228962068   1.71773909     2.67608948
## 692 458655.00 13.036054   0.148042369   1.88190136     1.68873109
## 693 461741.00 13.042759   0.672836882   2.95090813     1.84714001
## 694 462611.00 13.044642   0.188417316   3.44819104     2.86632549
## 695 462194.00 13.043740  -0.090140528   2.93234037     3.33325407
## 696 468582.00 13.057466   1.382103619   3.91250258     2.84880375
## 697 473392.00 13.067679   1.026501231   5.75614464     3.76518944
## 698 473460.00 13.067823   0.014364417   4.65679177     5.44284652
## 699 472283.00 13.065334  -0.248595446   4.74554544     4.44958391
## 700 474137.00 13.069252   0.392561240   4.81756182     4.53054630
## 701 471768.00 13.064243  -0.499644617   3.86538415     4.59613993
## 702 473656.00 13.068237   0.400196707   3.18673371     3.72153262
## 703 473637.00 13.068196  -0.004011350   3.41938569     3.08831726
## 704 474544.00 13.070110   0.191496864   3.46425963     3.30632953
## 705 484243.00 13.090342   2.043856839   4.87329477     3.34826697
## 706 484880.00 13.091657   0.131545526   4.81376362     4.64684053
## 707 489882.00 13.101920   1.031595446   5.99055808     4.59268273
## 708 493332.00 13.108938   0.704251228   5.28189303     5.65197333
## 709 491248.00 13.104704  -0.422433574   3.77192686     5.01690545
## 710 494424.00 13.111149   0.646516627   4.42782917     3.63482396
## 711 493527.00 13.109333  -0.181423232   4.49815047     4.24008543
## 712 494686.00 13.111678   0.234840242   4.33397942     4.30452640
## 713 500671.00 13.123704   1.209858375   6.12652829     4.15394816
## 714 499116.00 13.120594  -0.310583197   5.37520901     5.77285283
## 715 502596.00 13.127542   0.697232707   6.11417605     5.10101860
## 716 502503.00 13.127357  -0.018503928   5.89176135     5.76188430
## 717 500518.00 13.123399  -0.395022517   3.36091590     5.56394688
## 718 505965.00 13.134223   1.088272550   4.34849860     3.25163131
## 719 507282.00 13.136822   0.260294684   3.55187576     4.16728430
## 720 498336.00 13.119030  -1.763516151   1.01432707     3.43004483
## 721 501305.00 13.124970   0.595782765   2.04723480     1.00414178
## 722 503037.00 13.128419   0.345498250   1.74202709     2.00616391
## 723 509552.00 13.141287   1.295133360   3.24703613     1.71220010
## 724 510367.00 13.142885   0.159944422   3.16988959     3.14491946
## 725 512883.00 13.147803   0.492978582   2.43912669     3.07249489
## 726 513694.00 13.149383   0.158125732   2.92076391     2.38104987
## 727 518670.00 13.159023   0.968670064   3.19819497     2.83787625
## 728 521158.00 13.163809   0.479688434   3.71241565     3.09908034
## 729 517755.00 13.157257  -0.652968965   3.44383219     3.57952867
## 730 519519.00 13.160659   0.340701683   2.67884142     3.32918079
## 731 521774.00 13.164990   0.434055347   2.85679366     2.60895174
## 732 525903.00 13.172872   0.791338779   5.53180986     2.77744771
## 733 524063.00 13.169367  -0.349874406   4.53975125     5.24184118
## 734 526174.00 13.173387   0.402814165   4.59946286     4.34260766
## 735 480150.00 13.081854  -8.746916419  -5.77016673     4.39721461
## 736 407025.00 12.916630 -15.229615745 -20.24856623    -6.12350307
## 737 483066.00 13.087909  18.682144831  -5.81360661   -25.38959523
## 738 525093.00 13.171331   8.700053409   2.21902533    -6.17244849
## 739 536087.00 13.192052   2.093724350   3.35801184     2.17085354
## 740 540078.00 13.199469   0.744468715   3.63037697     3.24891296
## 741 551871.00 13.221070   2.183573484   6.58921691     3.50319769
## 742 550049.00 13.217763  -0.330149618   5.87658969     6.18187946
## 743 543834.00 13.206399  -1.129899336   4.22788410     5.55041460
## 744 542942.00 13.204758  -0.164020639   3.23995109     4.05638485
## 745 572822.00 13.258330   5.503350266   9.30403406     3.13827260
## 746 562686.00 13.240477  -1.769485111   6.93914941     8.51206832
## 747 625731.00 13.346676  11.204295113  30.31990003     6.48887657
## 748 625764.00 13.346729   0.005273832  53.74092500    23.26574838
## 749 622921.00 13.342175  -0.454324634  28.95153043    34.95551038
## 750 628881.00 13.351697   0.956782642  19.76564151    22.45148261
## 751 619014.00 13.335883  -1.568977279  15.46894441    16.50359925
## 752 624963.00 13.345448   0.961044500  15.71717419    13.39662754
## 753 631563.00 13.355953   1.056062519  14.44033116    13.58240408
## 754 640524.00 13.370042   1.418860826  16.44853459    12.61821861
## 755 646132.00 13.378759   0.875533157  18.81051939    14.12515378
## 756 639273.00 13.368087  -1.061547795  17.74241079    15.83236862
## 757 655154.00 13.392626   2.484228178  14.37305131    15.06883601
## 758 662321.00 13.403506   1.093941272  17.70703376    12.56681635
## 759 669958.00 13.414970   1.153066262   7.06805320    15.04330982
## 760 674719.00 13.422052   0.710641563   7.82323688     6.60145860
## 761 677115.00 13.425596   0.355110794   8.69997961     7.25561308
## 762 684084.00 13.435836   1.029219557   8.77797230     8.00366260
## 763 681108.00 13.431476  -0.435034294  10.03111400     8.06962303
## 764 685685.00 13.438174   0.671993282   9.71609519     9.11661587
## 765 684538.00 13.436499  -0.167277977   8.38792013     8.85566988
## 766 691844.00 13.447116   1.067289179   8.01219002     7.73879609
## 767 684411.00 13.436314  -1.074375148   5.92433125     7.41785720
## 768 676925.00 13.425316  -1.093787213   5.88981546     5.59298433
## 769 696982.00 13.454515   2.962957492   6.38445312     5.56221147
## 770        NA        NA            NA           NA     6.00130276
\end{verbatim}

\textit{Use the created function to create a dataframe with the various transformation for US industrial production (mnemonic INDPRO), plot the logged time series and the yearly changes produced by the function. Briefly describe the properties of the time series.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{industrial\_prod }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}\AttributeTok{date=}\FunctionTok{as.Date}\NormalTok{(fredmd}\SpecialCharTok{$}\NormalTok{sasdate, }\StringTok{"\%m/\%d/\%Y"}\NormalTok{),}\FunctionTok{input\_function}\NormalTok{(fredmd}\SpecialCharTok{$}\NormalTok{INDPRO))}
\FunctionTok{ggplot}\NormalTok{(industrial\_prod, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{date,}\AttributeTok{y=}\NormalTok{log\_ts))}\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{( }\AttributeTok{color=}\StringTok{"\#69b3a2"}\NormalTok{, }\AttributeTok{alpha=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{linetype=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Time Series of logged Industrial Production (INDPRO)"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"logged industrial production"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 row containing missing values (`geom_line()`).
\end{verbatim}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(industrial\_prod, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{date,}\AttributeTok{y=}\NormalTok{yoy\_growth))}\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{( }\AttributeTok{color=}\StringTok{"\#69b3a2"}\NormalTok{, }\AttributeTok{alpha=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{linetype=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Time Series of yoy change of Industrial Production (INDPRO)"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"yoy change of industrial production"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 13 rows containing missing values (`geom_line()`).
\end{verbatim}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-3-2.pdf}

\textit{Using suitable functions from the stats and urca package, assess the properties of both logged industrial production and its yearly growth rate. Plot the autocorrelation function and perform Dickey-Fuller tests to test for a unit root (note the different specifications, i.e. including a drift or a trend), interpret the results.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create time series object}
\NormalTok{log\_INDPRO }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(industrial\_prod}\SpecialCharTok{$}\NormalTok{log\_ts, }\AttributeTok{frequency =} \DecValTok{12}\NormalTok{, }\AttributeTok{start =} \FunctionTok{c}\NormalTok{(}\DecValTok{1959}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\NormalTok{yoy\_INDPRO }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(industrial\_prod}\SpecialCharTok{$}\NormalTok{yoy\_growth, }\AttributeTok{frequency =} \DecValTok{12}\NormalTok{, }\AttributeTok{start =} \FunctionTok{c}\NormalTok{(}\DecValTok{1959}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}

\CommentTok{\# Plot the time series}
\FunctionTok{plot}\NormalTok{(log\_INDPRO)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(yoy\_INDPRO)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-4-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the acf plots}
\FunctionTok{Acf}\NormalTok{(log\_INDPRO)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-4-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Acf}\NormalTok{(yoy\_INDPRO)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-4-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Dickey Fuller Test}
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(yoy\_INDPRO))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tseries::adf.test(na.omit(yoy_INDPRO)): p-value smaller than printed
## p-value
\end{verbatim}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  na.omit(yoy_INDPRO)
## Dickey-Fuller = -8.1782, Lag order = 9, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(log\_INDPRO))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  na.omit(log_INDPRO)
## Dickey-Fuller = -2.2774, Lag order = 9, p-value = 0.4609
## alternative hypothesis: stationary
\end{verbatim}

\textit{Estimate a suitable AR model (e.g. using the ar.ols() function) for the stationary time series (as determined in the previous point).1 How is the lag order determined by default? Use the estimated model to produce forecasts for the next year and plot them. Interpret their behaviour (i.e. are they converging towards a certain value? What could that be?). Use the produced forecasts to also forecast the change in the original time series.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1 }\OtherTok{\textless{}{-}} \FunctionTok{ar.ols}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(yoy\_INDPRO))}
\FunctionTok{summary}\NormalTok{(mod1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Length Class  Mode     
## order         1    -none- numeric  
## ar           26    -none- numeric  
## var.pred      1    -none- numeric  
## x.mean        1    -none- numeric  
## x.intercept   1    -none- numeric  
## aic          29    -none- numeric  
## n.used        1    -none- numeric  
## n.obs         1    -none- numeric  
## order.max     1    -none- numeric  
## partialacf    0    -none- NULL     
## resid       757    ts     numeric  
## method        1    -none- character
## series        1    -none- character
## frequency     1    -none- numeric  
## call          2    -none- call     
## asy.se.coef   2    -none- list
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## ar.ols(x = na.omit(yoy_INDPRO))
## 
## Coefficients:
##       1        2        3        4        5        6        7        8  
##  1.2847  -0.3585   0.0895   0.0178  -0.0729   0.0807  -0.0745  -0.0479  
##       9       10       11       12       13       14       15       16  
##  0.1280   0.0466  -0.1426  -0.6121   0.8016  -0.2314   0.1339  -0.0905  
##      17       18       19       20       21       22       23       24  
##  0.0297   0.0251  -0.1211   0.0515   0.0172   0.1285  -0.0857  -0.5370  
##      25       26  
##  0.6385  -0.1544  
## 
## Intercept: -0.009711 (0.03761) 
## 
## Order selected 26  sigma^2 estimated as  1.033
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{forecast}\NormalTok{(mod1, }\AttributeTok{h=}\DecValTok{12}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{window}\NormalTok{(yoy\_INDPRO, }\AttributeTok{start=}\FunctionTok{c}\NormalTok{(}\DecValTok{2000}\NormalTok{,}\DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-5-2.pdf}

\hypertarget{excercise-2}{%
\subsection{Excercise 2}\label{excercise-2}}

\textit{Read Kilian and Park (2009), who discuss the effects of oil price shocks on the US stock market, focus on Sections 2 and 3.1-3.3. Load the provided data by Kilian and Park (2009), which contains a measure of change in oil production, a measure of real economic activity, the real price of oil, and changes in real US dividend growth from 1973M1 to 2016M12.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Paket 'vars' wurde unter R Version 4.2.3 erstellt
\end{verbatim}

\begin{verbatim}
## Lade nötiges Paket: MASS
\end{verbatim}

\begin{verbatim}
## 
## Attache Paket: 'MASS'
\end{verbatim}

\begin{verbatim}
## Das folgende Objekt ist maskiert 'package:dplyr':
## 
##     select
\end{verbatim}

\begin{verbatim}
## Lade nötiges Paket: strucchange
\end{verbatim}

\begin{verbatim}
## Warning: Paket 'strucchange' wurde unter R Version 4.2.3 erstellt
\end{verbatim}

\begin{verbatim}
## Lade nötiges Paket: zoo
\end{verbatim}

\begin{verbatim}
## 
## Attache Paket: 'zoo'
\end{verbatim}

\begin{verbatim}
## Die folgenden Objekte sind maskiert von 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{verbatim}
## Lade nötiges Paket: sandwich
\end{verbatim}

\begin{verbatim}
## Warning: Paket 'sandwich' wurde unter R Version 4.2.3 erstellt
\end{verbatim}

\begin{verbatim}
## Lade nötiges Paket: lmtest
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"data\_kilian\_park\_2009.txt"}\NormalTok{)}
\CommentTok{\#("Global Oil Production Change","Global Real Activity", "Real Price of Oil", "US Dividend Returns")}
\FunctionTok{colnames}\NormalTok{(data) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"GOPC"}\NormalTok{,}\StringTok{"GRA"}\NormalTok{,}\StringTok{"RPO"}\NormalTok{,}\StringTok{"USSR"}\NormalTok{)}
\NormalTok{data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          GOPC      GRA       RPO    USSR
## 1     11.8773  34.5887  -46.3143 -1.3498
## 2      1.4191  40.0667  -46.6013 -0.3862
## 3      1.1777  42.5462  -45.3973  1.2771
## 4     27.4551  46.6761  -42.1724 -2.4366
## 5    -13.1104  50.6190  -39.8859 -0.2239
## 6     36.2581  51.5436  -39.3027  0.6786
## 7    -14.0844  56.2820  -41.0965 -0.7122
## 8     20.8365  61.7872  -35.8887 -1.0776
## 9    -23.7158  73.0504  -36.7697  0.7998
## 10   -59.7082  71.5685  -33.1236 -0.8792
## 11     9.1213  75.3892  -29.3632  0.4864
## 12    26.1767  71.4100   14.6552 -0.1892
## 13    10.1026  63.5861   39.6925 -0.0515
## 14     9.2310  67.3750   40.8650  0.2257
## 15    15.5441  61.8878   40.1608  0.4398
## 16     3.5458  69.1825   41.4577 -0.7320
## 17    -8.8526  59.3959   40.9448  0.3437
## 18   -23.2926  49.4722   37.9322 -0.3878
## 19   -31.9024  47.3110   36.1719  0.0317
## 20    11.8524  47.6495   33.5889  0.5552
## 21     3.7577  47.9757   32.0806 -0.5139
## 22     1.6349  46.3376   31.8258 -2.1276
## 23   -10.7655  25.4999   33.3402  0.2680
## 24   -48.8069  10.4380   32.1817 -1.0931
## 25   -23.3933   3.8215   33.7786 -0.0600
## 26    -1.9156  -9.7627   35.1462  0.3623
## 27    -8.9174 -23.3821   34.6174 -0.2930
## 28     5.5225 -26.0005   34.5043 -1.2231
## 29    29.9622 -18.9512   40.1747 -0.1163
## 30    31.1723 -23.7200   38.3928  0.4273
## 31    25.5941 -27.3742   39.5790 -2.5675
## 32    37.0258 -16.5595   37.3591  0.5383
## 33  -118.8875 -16.1659   41.1324  0.1205
## 34    41.3806  -7.6474   42.9655 -2.3702
## 35    16.2231 -17.6977   40.8834 -0.0993
## 36   -17.5549 -27.4741   29.5446  0.0350
## 37    31.9133 -31.7717   29.2902 -0.8525
## 38    29.5855 -14.7098   30.9793  0.2499
## 39   -22.1314 -11.5368   29.9087 -1.4075
## 40     5.1252  -3.6737   29.5246  2.4281
## 41    38.7579  -1.2650   29.5147 -0.2069
## 42     7.2057  -5.4346   29.2093 -1.1836
## 43     8.4737  -7.4425   29.2012  2.7918
## 44    18.5119  -8.0455   27.8657 -0.2326
## 45    36.2084  -4.9315   27.4946 -0.7857
## 46    11.1550  -3.7955   27.8147  4.9503
## 47    29.3070 -17.3901   28.2524 -0.4595
## 48  -113.3295 -29.9569   30.6158  0.6652
## 49    77.9832 -25.9164   32.3254  1.7763
## 50     9.7543 -26.1955   32.0962 -0.0187
## 51   -18.9504 -24.3904   30.1816  0.0458
## 52   -38.9876 -17.3683   31.6432  1.9229
## 53    18.3141 -21.5817   31.2145  0.2901
## 54   -23.1434 -25.0382   29.4127 -0.4181
## 55    16.9610 -27.5533   30.5689  1.1808
## 56    24.9204 -27.6545   29.0083  0.5950
## 57    -2.5589 -14.9057   28.9331 -0.1034
## 58    22.8363 -15.3274   28.6286  1.3293
## 59    24.0469 -19.2183   29.1674  0.4722
## 60  -113.8815 -19.6327   26.8880  0.1832
## 61    31.3925 -19.8845   25.6502  0.7266
## 62    10.4478 -20.2919   26.1215  0.3297
## 63    18.1129 -20.8518   24.1623  0.1724
## 64   -20.5883  -7.1184   23.9887  0.4114
## 65    28.0337  -3.1267   23.4231  0.6306
## 66    -8.5531  -9.5963   22.3123  0.8335
## 67    16.0520  -9.9796   21.4962 -0.3022
## 68    41.4259  -1.1979   21.0728  0.1982
## 69     8.2117  -4.1925   20.8605  1.3292
## 70     2.8199   5.2123   21.0152 -1.4269
## 71   -26.2241   3.1716   21.7721  0.4317
## 72   -30.3958  -3.2589   24.5721  0.7392
## 73     6.4666   0.2315   25.9774 -0.1932
## 74    22.8005  11.1971   28.2540  0.1314
## 75    23.8460  12.0734   34.1446  1.0175
## 76    -3.8809  22.5759   40.7855 -0.0750
## 77     4.8158  30.7292   49.8224 -0.2917
## 78    12.0123  34.0143   58.0655  0.6451
## 79    -2.4004  25.5783   60.8932  0.3452
## 80    -4.5874  28.4043   64.3531 -0.6278
## 81     8.4409  27.9531   63.2437  0.2644
## 82     6.1137  30.0995   69.7558 -0.3023
## 83    -8.7380  23.0999   75.3396  0.0287
## 84   -21.7808  22.2124   80.0896 -0.2218
## 85     7.0571  24.2538   84.0425  0.1812
## 86   -20.6162  24.5889   85.7593  0.2395
## 87   -24.7038  32.3338   85.1239  0.1987
## 88   -12.2343  33.2541   86.4680 -1.8715
## 89     4.6050  29.9806   85.9296  0.4781
## 90    -8.0201  24.7210   85.8954  0.3175
## 91    -3.2836  28.3563   84.9686 -1.4735
## 92   -23.4050  28.5760   84.1888  1.2244
## 93   -51.6351  28.1402   83.7319  0.1015
## 94    17.6290  31.8145   83.9945 -1.7831
## 95    28.8526  32.9034   84.5915  0.2496
## 96    -3.2334  30.7622   92.3218 -0.6683
## 97     5.4779  29.4822   91.7939 -0.3753
## 98    13.3926  24.3853   89.3293  0.4512
## 99   -20.6951  22.3265   89.0273 -0.4185
## 100  -16.9264  17.5898   86.8610 -0.3465
## 101  -14.4817  19.6307   83.8093  0.5155
## 102  -27.9060  15.3921   81.4877 -1.0676
## 103  -20.6039   6.6868   78.6261  0.8895
## 104    2.4594   5.3035   76.5881 -0.3900
## 105    8.0737   6.5531   76.2382 -0.1528
## 106  -12.6864   5.9993   77.9885 -0.2738
## 107   21.2956   2.4581   76.9485 -0.2838
## 108   -5.5340   0.0539   75.4832 -0.7006
## 109  -14.0946  -5.0174   74.9970  0.2057
## 110  -41.1448   0.1184   70.9418  0.2774
## 111  -30.2036   4.2208   66.8876 -0.8120
## 112   19.7568   2.2939   65.8227  1.4846
## 113   44.1581 -11.4008   67.7168 -0.9844
## 114   -9.4134 -26.7396   66.1615 -0.0591
## 115   -1.7563 -28.2952   64.4804  0.3021
## 116   -3.2719 -17.8384   64.7229 -0.3019
## 117   38.1825 -17.5196   65.0684 -0.9621
## 118   12.8232 -15.7633   64.5978  1.2041
## 119  -24.8338 -12.6546   64.1765 -0.8041
## 120  -33.2395 -11.4116   59.4576  1.1904
## 121  -69.0584  -8.5022   57.2962 -0.7997
## 122   22.0536  -6.7778   49.3172 -0.0563
## 123    5.2623  -5.4623   46.9034 -0.0769
## 124   39.3751  -5.6232   48.5533 -2.0575
## 125    4.7755 -14.1820   50.7758  1.5666
## 126   39.7987 -21.2151   48.7532 -0.3438
## 127   -3.3638 -21.8777   50.9935 -1.6505
## 128   14.3132 -19.9310   50.8297  1.7730
## 129   -5.6917 -18.0920   50.8712 -0.6758
## 130    8.0173 -13.5974   48.5999 -1.1741
## 131  -17.6080 -19.9193   49.0229  2.1798
## 132    2.5347 -18.8822   46.6137  0.0114
## 133    7.6944 -14.9021   46.5064 -1.8979
## 134   -6.0901 -12.3886   46.3527  0.6959
## 135    4.3626 -10.1388   46.5159  0.8509
## 136   -8.3664 -10.4529   46.8364 -0.8939
## 137   27.8148 -15.5863   46.4038  0.8987
## 138  -15.6032 -18.5914   45.3658  0.8545
## 139  -37.1714 -18.0560   44.8018 -0.6967
## 140   10.2828 -16.1322   43.7512 -0.3899
## 141    9.1333 -15.3968   43.6830  2.4128
## 142    0.3763 -10.9428   43.3191 -2.4353
## 143   -0.8855 -12.7136   40.5922  0.7609
## 144  -27.6788 -14.7531   38.4932  0.6535
## 145   32.8469 -16.3405   36.0916 -0.0077
## 146    4.8175 -14.4116   36.3973  0.3751
## 147   -9.3888 -11.1324   37.6339  0.4651
## 148  -32.2238 -11.4375   37.4834  0.0607
## 149  -33.6271 -17.2801   35.9277 -0.3905
## 150   23.8140 -29.6160   33.2148  1.0126
## 151   -3.1434 -33.9720   33.1797  0.1198
## 152   42.4336 -27.4539   32.8064  0.2537
## 153   36.7761 -19.6688   33.2993 -0.6448
## 154   10.2367 -19.2687   34.0638  1.0428
## 155    6.6985 -19.7799   30.1931  0.0024
## 156  -22.4386 -20.8163   24.8215  0.0166
## 157    0.2160 -28.9999   -6.9571  0.7193
## 158  -10.7820 -32.8211  -30.5901 -0.2794
## 159    2.2642 -38.1711  -38.0456  1.1478
## 160   25.3742 -40.6852  -38.1692 -0.4727
## 161   16.3078 -41.2501  -45.7771  0.7567
## 162   23.6519 -46.4061  -57.4530  0.6942
## 163   13.3759 -42.6126  -49.1109 -0.7475
## 164  -84.9905 -27.5092  -41.5422  0.3664
## 165    7.7588 -27.1514  -42.2701  1.4519
## 166   19.9926 -28.7481  -37.2673  1.7769
## 167    3.6266 -28.4058  -32.4885  0.4672
## 168  -14.9135 -23.3384  -18.1087 -0.2425
## 169  -15.1199 -22.7570  -15.2961 -0.3118
## 170  -16.3097 -18.1825  -14.0177  1.0896
## 171   14.8222 -12.6141  -10.8773  1.3222
## 172   17.4707  -6.1833   -9.1508 -0.1157
## 173   -6.4675 -12.0460   -7.1030  0.3206
## 174   54.3186 -13.7465   -4.4698  1.1188
## 175   16.4083  -3.5026   -4.5971  0.8584
## 176  -12.4762  -4.3086   -8.9058  0.6978
## 177    4.0222  -0.2110   -9.3827  0.2142
## 178   -9.5514   1.7900  -11.8571 -0.6772
## 179    1.5350   3.8275  -17.3512  0.0118
## 180  -16.2777   5.4727  -28.4267  0.4646
## 181    1.6800   9.6313  -28.7285  4.8320
## 182    7.5517  11.2830  -33.6291 -0.2892
## 183    6.4679   9.3490  -28.3615 -1.1941
## 184   -5.8842   8.1051  -26.6520  1.5327
## 185   -7.0028  -0.1369  -29.8130 -0.5213
## 186    8.8564  -1.4572  -34.7896  1.3382
## 187   23.8195   0.3147  -38.5752  1.2368
## 188    7.2006   1.5229  -42.4039 -0.2181
## 189   33.6546   5.5153  -48.6156  1.9513
## 190    9.0171   9.6112  -51.9827  2.0086
## 191    4.8244   9.2331  -41.4710  1.8615
## 192  -57.7846  12.1730  -29.0642  2.7347
## 193   -9.8360   8.3708  -25.9018 -3.8553
## 194    8.2603  12.2252  -19.6433  0.5756
## 195    8.7732  12.2065  -10.6263  0.6409
## 196   -1.6070  13.0137  -13.9078  2.2969
## 197    0.7529   6.2677  -18.4113  0.5740
## 198   10.4915   4.3908  -20.2775 -0.5638
## 199   17.8543   8.2841  -24.5939  0.4446
## 200    1.6479   8.3546  -22.5963  1.2291
## 201   11.2562   9.8923  -19.3440 -1.6971
## 202   14.8459  13.7453  -19.5780 -1.8325
## 203   -6.9508  12.4934  -10.8716 -0.4515
## 204  -10.9423  13.6688   -9.5489 -1.6121
## 205    5.0613  11.3698  -13.5645  0.8755
## 206   17.5930  11.1547  -18.3716 -0.3842
## 207   -5.3563   6.5573  -31.4312  1.3336
## 208  -11.0697   0.4860  -35.1919 -1.3531
## 209  -16.3565  -4.0500  -41.7050  0.2016
## 210    2.0727 -10.7565  -33.3877  0.1083
## 211  -72.5080 -10.5636    4.0776 -0.8650
## 212   52.5156 -12.4950   24.2321 -1.8725
## 213    6.8411  -9.9598   33.1227 -0.0981
## 214   16.2920  -7.6881   24.3627  0.0227
## 215    4.1772  -2.3704    7.3412 -0.0043
## 216   -3.5750  -0.8303   -6.6749 -0.1125
## 217   -6.1641   2.4109  -26.5177 -0.1394
## 218    5.0641   2.8235  -30.5316 -0.6551
## 219  -28.0234   0.3280  -26.6307 -0.2138
## 220   -3.5936   0.8109  -26.7821 -1.3544
## 221    3.9094   1.2830  -30.2866 -0.7326
## 222   19.9560  -2.7112  -28.4291 -1.3021
## 223  -13.9620  -5.2202  -25.6284 -0.3020
## 224   20.7697  -3.3579  -24.3828  0.6719
## 225   -0.8846  -2.7257  -20.1018 -1.4134
## 226    4.8657  -0.1137  -23.1397 -0.2078
## 227    8.0358  -3.7924  -35.3824 -0.5660
## 228    1.3348  -8.2259  -41.8892 -0.8257
## 229  -16.5117 -12.9933  -42.7289 -1.0487
## 230  -12.9648 -16.0288  -40.8639  1.0894
## 231    7.2050 -18.2071  -35.0889 -1.5551
## 232  -22.7259 -15.0158  -27.4458 -0.6502
## 233    4.9218 -18.4279  -22.3446  0.9342
## 234    9.3791 -21.5758  -23.0846 -0.5247
## 235   -0.2662 -22.1123  -25.8115 -0.5766
## 236    5.2457 -19.7018  -25.9724  0.4128
## 237   15.8601 -18.3436  -25.9822 -0.3521
## 238   -5.7213 -14.0917  -31.2466  0.2184
## 239    6.3474  -8.1469  -39.6545 -0.5158
## 240   -3.6506  -8.5228  -40.8352 -0.2789
## 241    7.0129  -8.7563  -37.4785 -0.6247
## 242  -14.1536  -6.5585  -35.2905  0.9098
## 243  -14.0878  -6.1234  -32.7079 -0.3766
## 244    3.7493  -4.7060  -35.5245  0.2341
## 245   -5.7215  -7.3714  -41.8801 -0.1125
## 246   12.1721 -11.2516  -48.0922 -0.1666
## 247   -3.5551 -14.0249  -49.3807 -0.1834
## 248    0.2267 -10.6046  -51.5860  0.1923
## 249    9.2548 -12.4592  -50.2519  0.1059
## 250    1.2685 -14.3163  -60.9270 -0.0287
## 251    7.6713 -16.2721  -72.3428 -0.2706
## 252    3.8237 -18.9247  -69.4395  0.5998
## 253   -3.5338 -21.7225  -69.9448 -0.0050
## 254   -1.7991 -19.6030  -68.0698 -0.9115
## 255   -9.1478 -17.0677  -58.3174  0.3742
## 256    8.7956 -11.6074  -50.5909 -0.0006
## 257    6.2148 -14.5579  -42.9258 -0.2389
## 258   -7.8783 -14.1216  -40.4854 -0.1322
## 259   -2.1332  -9.8904  -45.9221 -0.2677
## 260   11.9974  -4.8758  -50.7295  0.0337
## 261    9.7273   0.3943  -48.5590  0.6332
## 262    3.3913   2.4266  -47.6653 -0.7813
## 263    6.2254   5.0480  -52.0844  1.1528
## 264   -7.6481   1.8748  -47.5259  0.4704
## 265   10.0589  -0.1756  -43.9412 -0.6573
## 266  -14.5042   5.9310  -44.1398  0.2822
## 267   15.5382   3.9683  -36.2326  0.3605
## 268    0.0913   2.7795  -37.1815  0.0367
## 269  -16.6529  -3.2822  -43.6601 -0.1408
## 270   18.4558  -2.1172  -49.2745  2.9452
## 271    2.5209  -1.7356  -49.2288  0.2609
## 272    7.5543  -3.3246  -48.3370 -0.1490
## 273   -6.5197  -7.4535  -51.1435  0.3714
## 274    3.7968  -8.3648  -49.8716  0.5994
## 275    7.4354  -9.8243  -44.0675 -0.2607
## 276   -1.3763 -11.8902  -44.8716  0.3544
## 277    7.5297 -13.9418  -43.4199  0.6799
## 278   -2.8170 -11.0028  -32.4212 -0.0515
## 279   -2.7986 -11.4334  -25.8668  0.4006
## 280    0.0048 -12.7464  -31.8988  0.1787
## 281    6.0519 -19.0183  -36.1478 -0.0962
## 282    1.6291 -25.7201  -34.9002 -0.5492
## 283   -6.2117 -22.9472  -30.3917 -1.0748
## 284    8.8928 -22.4957  -23.6121  0.8151
## 285    6.7032 -20.6082  -18.7132  0.9778
## 286    8.3749  -9.9023  -21.4700 -0.7831
## 287   10.6044  -8.2201  -19.2805  0.6697
## 288   -1.2363  -7.2501  -20.3339 -0.3131
## 289    6.5638 -10.2617  -30.2791 -0.3388
## 290   -0.2586  -8.9827  -38.9384  0.9990
## 291    9.6053 -10.1387  -46.1952  0.4639
## 292  -11.9557  -9.6977  -42.2364 -0.8543
## 293  -14.2462  -9.8780  -49.1116  0.4620
## 294    8.2447  -6.5220  -48.4327  0.9132
## 295   16.1513  -5.6020  -46.0300 -0.7325
## 296    6.3740  -3.3093  -46.8928  0.6185
## 297    9.3538  -4.3983  -42.2664  0.2172
## 298   -2.6286  -5.0094  -47.0346 -0.3505
## 299   -3.3763  -6.4122  -58.5188  0.8895
## 300   21.9689  -9.4627  -69.3527  0.1312
## 301    6.5100 -18.2077  -76.6615  0.4292
## 302   -2.0770 -19.1250  -84.3036 -0.1088
## 303   -2.4403 -23.2334  -80.6890  1.0886
## 304   -9.5455 -24.2498  -82.5089 -0.3698
## 305   -4.9416 -29.4978  -90.8941  0.8013
## 306   -2.3260 -33.0428  -91.6577 -0.5946
## 307  -17.9280 -30.5189  -93.6150  0.7421
## 308    1.5807 -22.1184  -81.8000  0.5726
## 309    2.1614 -19.6335  -87.3511 -0.3958
## 310   15.2366 -23.0108  -97.1776  0.2405
## 311   -3.1666 -22.7422 -113.0943 -0.0426
## 312    3.8029 -31.3305 -105.3953  0.4444
## 313    5.7582 -31.0532 -103.7359 -0.3307
## 314   -5.7633 -23.5925  -87.9813  0.9670
## 315  -26.1466 -28.7460  -68.3693 -0.8216
## 316   -3.5337 -21.3651  -63.4927  4.1501
## 317  -19.3280 -26.8972  -61.3326  0.1646
## 318   27.9638 -24.2267  -49.1336  0.1663
## 319   -2.0152 -19.7934  -41.3391  0.0505
## 320    0.8071 -15.1885  -31.6515  0.4838
## 321    9.2257  -3.8654  -31.9226 -0.3042
## 322   -0.3797  -3.6368  -25.3065  0.3308
## 323  -14.7931  -1.6797  -20.4468 -0.1240
## 324   17.8042  -4.4078  -16.9549 -0.2068
## 325   11.2977  -1.6471   -9.3906  0.2858
## 326    0.5775   3.2992   -8.8517 -0.8092
## 327   11.9809   3.7061  -21.9299  0.9746
## 328    8.9070   1.6754  -13.9650 -3.2818
## 329   -3.6317   1.1267   -5.2755 -2.0617
## 330   10.9162   2.4328   -8.7637 -1.1845
## 331   14.2230   3.7559   -5.9466  0.9349
## 332    0.6605   5.6916   -0.5347 -2.7651
## 333    7.5393   7.1658   -3.5282 -0.2000
## 334    9.3121   7.9409   -2.7292  0.4649
## 335  -21.7043   4.0567  -20.4336 -1.8640
## 336   -2.1978   0.9142  -23.8229  0.2696
## 337   -8.3383  -2.6774  -22.1095 -0.8529
## 338   11.8623  -2.9722  -30.3409 -2.0247
## 339  -15.5797  -4.2146  -30.5980 -0.7566
## 340  -12.3518  -3.3928  -24.2164 -0.2743
## 341  -27.6358  -4.7544  -27.2414 -1.1950
## 342   34.9737  -9.8616  -32.1688  0.6725
## 343    3.1832 -19.0790  -27.8268 -0.6892
## 344   -6.6428 -20.0923  -33.6671  0.6262
## 345   -2.0532 -21.7280  -51.6092  0.1664
## 346    4.3700 -23.5373  -67.0925 -1.7176
## 347   -7.7065 -23.8131  -67.7234  0.9581
## 348  -15.7840 -20.6519  -61.2819  0.3283
## 349    1.2662 -18.0424  -54.6452  0.1890
## 350   -3.3499 -12.6889  -34.8736 -0.7515
## 351  -10.3448 -11.7097  -28.0126 -0.7939
## 352   11.1282 -15.0435  -26.2240 -0.9355
## 353   -2.6840 -15.4062  -30.4147  2.4814
## 354    8.5060 -15.7509  -24.2767  0.1947
## 355   -4.8079 -14.8897  -21.8304 -1.6301
## 356   10.5097  -8.0870  -16.4668  0.4329
## 357   23.4630  -1.6184  -21.0175  0.7565
## 358    2.1602   0.6567  -30.4910 -0.2813
## 359  -29.5273   5.4544  -18.7279  0.4995
## 360    9.6565   7.5929   -6.2792 -0.2806
## 361   27.6204   7.2509   -0.6512  0.0101
## 362    9.0965  10.8899  -10.8026  0.7653
## 363  -18.5304  14.4921  -28.1553  1.9666
## 364    0.2274  17.4164  -25.4006 -0.2160
## 365  -13.9197  16.4065  -17.6003  0.9148
## 366   10.7471  16.4934  -15.1717  0.7912
## 367    7.9993  18.6683  -13.6031  0.4163
## 368   12.1422  19.9859  -24.3708  1.0417
## 369   14.7763  34.4858  -18.0482  1.9429
## 370    3.5475  37.1173  -17.3924  1.0704
## 371   21.3649  39.3514  -13.5267  1.5156
## 372   -5.2978  43.8080   -8.8637  0.5157
## 373   -0.6099  44.8876   -7.2780  0.8421
## 374   -0.4285  42.0271   -2.9740  1.9596
## 375   -0.9510  38.1499   -2.5760  1.1011
## 376   -5.2012  31.7228    6.6676  1.7399
## 377   26.6435  26.3571   -0.1567  1.2570
## 378    5.7723  33.2833    6.8840 -0.3775
## 379  -15.2827  36.6318   16.3141  1.7123
## 380   10.2278  35.9975   18.5595  0.4149
## 381    8.1693  37.6990   29.5119 -0.5829
## 382   -5.7427  43.6607   16.3997 13.4084
## 383   -6.1610  44.8616    0.6289  1.2392
## 384    8.1848  39.1524   10.3545 -0.5285
## 385    4.4601  39.5796   15.5553  2.0526
## 386    5.3401  39.9305   29.1341  1.8393
## 387    5.4299  40.0753   27.5026  0.3292
## 388    2.7705  35.8536   22.7843  0.7772
## 389   -6.4420  25.0475   36.1375  0.7380
## 390   -2.1333  19.6901   42.6227  0.2382
## 391    1.1567  18.0382   52.4338  1.7932
## 392   -6.3020  24.2635   51.4393 -0.3011
## 393    0.6710  28.1976   45.0359 -0.1847
## 394    7.8273  27.0911   35.5375 -7.5283
## 395    4.6396  22.2818   37.3338 -0.5679
## 396   -8.6447  17.7115   46.1974  1.4729
## 397   -1.8932  20.2052   40.4418  1.2934
## 398   -3.3859  22.6103   44.8353 -0.3981
## 399    1.0315  20.3966   56.3131  1.1522
## 400   -3.5731  19.3941   58.8900  2.1988
## 401   -0.9524  21.9870   57.9883 -0.2004
## 402   14.0616  25.5455   63.6884 -0.0572
## 403   -4.0986  31.6388   60.7105  1.4046
## 404   -2.1525  34.6689   46.8113  0.6278
## 405    1.0604  36.2666   38.9242  0.0782
## 406   -8.2141  37.4276   38.5136  2.1585
## 407   -0.0164  38.4130   42.6645  1.5243
\end{verbatim}

\begin{itemize}
\item Using the the packages vars in R (or an equivalent one in another language), estimate the VAR described in section 2.2 using the variables in the same order as specified by Kilian and Park (2009).

```r
mod1 <- VAR(data, p=24, type="const")
summary(mod1)
```

```
## 
## VAR Estimation Results:
## ========================= 
## Endogenous variables: GOPC, GRA, RPO, USSR 
## Deterministic variables: const 
## Sample size: 383 
## Log Likelihood: -4332.408 
## Roots of the characteristic polynomial:
## 0.9869 0.9761 0.9761 0.9749 0.9749 0.9745 0.9745 0.9704 0.9704 0.9696 0.9696 0.9693 0.9693 0.9685 0.9685 0.9671 0.9671 0.9645 0.9645 0.9631 0.9631 0.9606 0.9606 0.9589 0.9589 0.9579 0.9579 0.9556 0.9556 0.9531 0.9531 0.9528 0.9528 0.9492 0.9492 0.9474 0.9474 0.9443 0.9443 0.9426 0.9426 0.9426 0.9426 0.9399 0.9399 0.9392 0.9392 0.9369 0.9369 0.9365 0.9365 0.9328 0.9328 0.9312 0.9312 0.9301 0.9301 0.9289 0.9289 0.9285 0.9285 0.9245 0.9245 0.9223 0.9223 0.9197 0.9197 0.9164 0.9164 0.9126 0.9126 0.9114 0.9114 0.9088 0.9088 0.9053 0.9053 0.8838 0.8838 0.8784 0.8784 0.8761 0.8761 0.8759 0.8641 0.8641 0.8606 0.8606 0.8425 0.8425 0.7856 0.7856 0.7718 0.7718 0.6814 0.4664
## Call:
## VAR(y = data, p = 24, type = "const")
## 
## 
## Estimation results for equation GOPC: 
## ===================================== 
## GOPC = GOPC.l1 + GRA.l1 + RPO.l1 + USSR.l1 + GOPC.l2 + GRA.l2 + RPO.l2 + USSR.l2 + GOPC.l3 + GRA.l3 + RPO.l3 + USSR.l3 + GOPC.l4 + GRA.l4 + RPO.l4 + USSR.l4 + GOPC.l5 + GRA.l5 + RPO.l5 + USSR.l5 + GOPC.l6 + GRA.l6 + RPO.l6 + USSR.l6 + GOPC.l7 + GRA.l7 + RPO.l7 + USSR.l7 + GOPC.l8 + GRA.l8 + RPO.l8 + USSR.l8 + GOPC.l9 + GRA.l9 + RPO.l9 + USSR.l9 + GOPC.l10 + GRA.l10 + RPO.l10 + USSR.l10 + GOPC.l11 + GRA.l11 + RPO.l11 + USSR.l11 + GOPC.l12 + GRA.l12 + RPO.l12 + USSR.l12 + GOPC.l13 + GRA.l13 + RPO.l13 + USSR.l13 + GOPC.l14 + GRA.l14 + RPO.l14 + USSR.l14 + GOPC.l15 + GRA.l15 + RPO.l15 + USSR.l15 + GOPC.l16 + GRA.l16 + RPO.l16 + USSR.l16 + GOPC.l17 + GRA.l17 + RPO.l17 + USSR.l17 + GOPC.l18 + GRA.l18 + RPO.l18 + USSR.l18 + GOPC.l19 + GRA.l19 + RPO.l19 + USSR.l19 + GOPC.l20 + GRA.l20 + RPO.l20 + USSR.l20 + GOPC.l21 + GRA.l21 + RPO.l21 + USSR.l21 + GOPC.l22 + GRA.l22 + RPO.l22 + USSR.l22 + GOPC.l23 + GRA.l23 + RPO.l23 + USSR.l23 + GOPC.l24 + GRA.l24 + RPO.l24 + USSR.l24 + const 
## 
##           Estimate Std. Error t value Pr(>|t|)    
## GOPC.l1  -0.129498   0.058658  -2.208 0.028060 *  
## GRA.l1   -0.221827   0.266750  -0.832 0.406334    
## RPO.l1   -0.477407   0.190269  -2.509 0.012656 *  
## USSR.l1  -0.453988   0.975409  -0.465 0.641975    
## GOPC.l2  -0.132503   0.057952  -2.286 0.022961 *  
## GRA.l2    0.460494   0.409188   1.125 0.261369    
## RPO.l2    0.854052   0.329495   2.592 0.010032 *  
## USSR.l2   1.170992   0.977994   1.197 0.232165    
## GOPC.l3  -0.285100   0.058954  -4.836 2.17e-06 ***
## GRA.l3   -0.411880   0.402039  -1.024 0.306475    
## RPO.l3   -0.574777   0.350788  -1.639 0.102410    
## USSR.l3   0.467702   0.986845   0.474 0.635907    
## GOPC.l4  -0.103021   0.061469  -1.676 0.094836 .  
## GRA.l4    0.032507   0.399724   0.081 0.935241    
## RPO.l4    0.276691   0.351854   0.786 0.432294    
## USSR.l4   1.384134   1.021778   1.355 0.176604    
## GOPC.l5  -0.256445   0.059789  -4.289 2.46e-05 ***
## GRA.l5    0.246985   0.401258   0.616 0.538697    
## RPO.l5   -0.269018   0.347805  -0.773 0.439881    
## USSR.l5   1.252854   1.031197   1.215 0.225387    
## GOPC.l6  -0.080966   0.061146  -1.324 0.186510    
## GRA.l6   -0.289052   0.401867  -0.719 0.472560    
## RPO.l6    0.535320   0.348479   1.536 0.125604    
## USSR.l6   0.671933   1.031420   0.651 0.515270    
## GOPC.l7  -0.119813   0.060060  -1.995 0.047005 *  
## GRA.l7    0.575549   0.400876   1.436 0.152172    
## RPO.l7   -0.243980   0.350685  -0.696 0.487166    
## USSR.l7   0.093727   1.033083   0.091 0.927774    
## GOPC.l8  -0.072798   0.059515  -1.223 0.222263    
## GRA.l8   -0.273770   0.400626  -0.683 0.494935    
## RPO.l8   -0.233840   0.351327  -0.666 0.506210    
## USSR.l8  -0.069432   1.052360  -0.066 0.947442    
## GOPC.l9   0.096222   0.059203   1.625 0.105204    
## GRA.l9   -0.215352   0.398761  -0.540 0.589581    
## RPO.l9    0.126854   0.351486   0.361 0.718436    
## USSR.l9   1.658440   1.048687   1.581 0.114882    
## GOPC.l10 -0.035560   0.058108  -0.612 0.541045    
## GRA.l10   0.067917   0.391630   0.173 0.862443    
## RPO.l10   0.182622   0.348680   0.524 0.600856    
## USSR.l10 -0.061630   1.040533  -0.059 0.952811    
## GOPC.l11 -0.114046   0.058097  -1.963 0.050611 .  
## GRA.l11   0.062443   0.385908   0.162 0.871571    
## RPO.l11  -0.315856   0.351091  -0.900 0.369068    
## USSR.l11 -0.145423   1.031966  -0.141 0.888034    
## GOPC.l12  0.209483   0.058398   3.587 0.000393 ***
## GRA.l12  -0.166625   0.382032  -0.436 0.663053    
## RPO.l12   0.406722   0.354808   1.146 0.252623    
## USSR.l12 -0.108427   1.022965  -0.106 0.915662    
## GOPC.l13 -0.022224   0.058745  -0.378 0.705474    
## GRA.l13   0.333735   0.379553   0.879 0.379986    
## RPO.l13  -0.225130   0.350101  -0.643 0.520710    
## USSR.l13  0.154391   1.005844   0.153 0.878117    
## GOPC.l14 -0.095299   0.058918  -1.617 0.106878    
## GRA.l14  -0.899450   0.382447  -2.352 0.019360 *  
## RPO.l14  -0.177207   0.344246  -0.515 0.607113    
## USSR.l14 -0.487767   1.116605  -0.437 0.662564    
## GOPC.l15  0.170775   0.059296   2.880 0.004277 ** 
## GRA.l15   0.233980   0.385337   0.607 0.544194    
## RPO.l15   0.061130   0.350925   0.174 0.861835    
## USSR.l15  1.635650   1.124519   1.455 0.146895    
## GOPC.l16 -0.084994   0.060090  -1.414 0.158320    
## GRA.l16   0.183684   0.384496   0.478 0.633209    
## RPO.l16   0.297773   0.353849   0.842 0.400756    
## USSR.l16  1.174337   1.160704   1.012 0.312515    
## GOPC.l17 -0.010691   0.058759  -0.182 0.855754    
## GRA.l17  -0.462543   0.385539  -1.200 0.231236    
## RPO.l17  -0.416688   0.356992  -1.167 0.244094    
## USSR.l17  1.789003   1.166427   1.534 0.126198    
## GOPC.l18 -0.031792   0.057471  -0.553 0.580570    
## GRA.l18   0.993036   0.385989   2.573 0.010595 *  
## RPO.l18   0.654656   0.356477   1.836 0.067328 .  
## USSR.l18  0.847356   1.168428   0.725 0.468916    
## GOPC.l19 -0.008979   0.057203  -0.157 0.875386    
## GRA.l19  -1.500210   0.385719  -3.889 0.000125 ***
## RPO.l19  -0.615006   0.358608  -1.715 0.087432 .  
## USSR.l19 -1.275622   1.130342  -1.129 0.260043    
## GOPC.l20 -0.029677   0.056751  -0.523 0.601426    
## GRA.l20   0.887459   0.393212   2.257 0.024766 *  
## RPO.l20   0.319920   0.360016   0.889 0.374951    
## USSR.l20  0.141381   1.130968   0.125 0.900604    
## GOPC.l21 -0.102112   0.055969  -1.824 0.069129 .  
## GRA.l21   0.636615   0.399207   1.595 0.111884    
## RPO.l21  -0.277640   0.358074  -0.775 0.438761    
## USSR.l21 -0.438823   1.107180  -0.396 0.692147    
## GOPC.l22 -0.042981   0.054458  -0.789 0.430621    
## GRA.l22  -1.130261   0.396723  -2.849 0.004704 ** 
## RPO.l22   0.325394   0.358129   0.909 0.364329    
## USSR.l22 -0.173196   1.086725  -0.159 0.873487    
## GOPC.l23 -0.020762   0.054437  -0.381 0.703192    
## GRA.l23   0.830848   0.398004   2.088 0.037725 *  
## RPO.l23  -0.017338   0.341044  -0.051 0.959489    
## USSR.l23 -0.071287   1.078487  -0.066 0.947345    
## GOPC.l24 -0.039888   0.054093  -0.737 0.461487    
## GRA.l24  -0.126947   0.261165  -0.486 0.627282    
## RPO.l24  -0.244923   0.193333  -1.267 0.206241    
## USSR.l24 -1.610127   1.054845  -1.526 0.128013    
## const     0.433333   1.149328   0.377 0.706430    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## 
## Residual standard error: 18.91 on 286 degrees of freedom
## Multiple R-Squared: 0.3704,  Adjusted R-squared: 0.159 
## F-statistic: 1.752 on 96 and 286 DF,  p-value: 0.0002078 
## 
## 
## Estimation results for equation GRA: 
## ==================================== 
## GRA = GOPC.l1 + GRA.l1 + RPO.l1 + USSR.l1 + GOPC.l2 + GRA.l2 + RPO.l2 + USSR.l2 + GOPC.l3 + GRA.l3 + RPO.l3 + USSR.l3 + GOPC.l4 + GRA.l4 + RPO.l4 + USSR.l4 + GOPC.l5 + GRA.l5 + RPO.l5 + USSR.l5 + GOPC.l6 + GRA.l6 + RPO.l6 + USSR.l6 + GOPC.l7 + GRA.l7 + RPO.l7 + USSR.l7 + GOPC.l8 + GRA.l8 + RPO.l8 + USSR.l8 + GOPC.l9 + GRA.l9 + RPO.l9 + USSR.l9 + GOPC.l10 + GRA.l10 + RPO.l10 + USSR.l10 + GOPC.l11 + GRA.l11 + RPO.l11 + USSR.l11 + GOPC.l12 + GRA.l12 + RPO.l12 + USSR.l12 + GOPC.l13 + GRA.l13 + RPO.l13 + USSR.l13 + GOPC.l14 + GRA.l14 + RPO.l14 + USSR.l14 + GOPC.l15 + GRA.l15 + RPO.l15 + USSR.l15 + GOPC.l16 + GRA.l16 + RPO.l16 + USSR.l16 + GOPC.l17 + GRA.l17 + RPO.l17 + USSR.l17 + GOPC.l18 + GRA.l18 + RPO.l18 + USSR.l18 + GOPC.l19 + GRA.l19 + RPO.l19 + USSR.l19 + GOPC.l20 + GRA.l20 + RPO.l20 + USSR.l20 + GOPC.l21 + GRA.l21 + RPO.l21 + USSR.l21 + GOPC.l22 + GRA.l22 + RPO.l22 + USSR.l22 + GOPC.l23 + GRA.l23 + RPO.l23 + USSR.l23 + GOPC.l24 + GRA.l24 + RPO.l24 + USSR.l24 + const 
## 
##            Estimate Std. Error t value Pr(>|t|)    
## GOPC.l1   0.0042092  0.0128159   0.328  0.74282    
## GRA.l1    1.1812029  0.0582812  20.267  < 2e-16 ***
## RPO.l1    0.1136618  0.0415712   2.734  0.00664 ** 
## USSR.l1   0.0604760  0.2131134   0.284  0.77679    
## GOPC.l2   0.0125577  0.0126618   0.992  0.32214    
## GRA.l2   -0.2114997  0.0894018  -2.366  0.01866 *  
## RPO.l2   -0.1690809  0.0719900  -2.349  0.01952 *  
## USSR.l2   0.2977945  0.2136781   1.394  0.16450    
## GOPC.l3   0.0317651  0.0128806   2.466  0.01425 *  
## GRA.l3   -0.0412306  0.0878399  -0.469  0.63915    
## RPO.l3    0.1029446  0.0766422   1.343  0.18028    
## USSR.l3   0.0388804  0.2156120   0.180  0.85702    
## GOPC.l4  -0.0082946  0.0134302  -0.618  0.53733    
## GRA.l4    0.0545079  0.0873342   0.624  0.53304    
## RPO.l4    0.0124102  0.0768751   0.161  0.87187    
## USSR.l4   0.2630997  0.2232442   1.179  0.23957    
## GOPC.l5  -0.0185343  0.0130630  -1.419  0.15704    
## GRA.l5   -0.0689038  0.0876693  -0.786  0.43255    
## RPO.l5   -0.0532697  0.0759906  -0.701  0.48387    
## USSR.l5   0.2004175  0.2253021   0.890  0.37446    
## GOPC.l6  -0.0069733  0.0133595  -0.522  0.60209    
## GRA.l6    0.0342413  0.0878024   0.390  0.69684    
## RPO.l6    0.0108841  0.0761378   0.143  0.88643    
## USSR.l6  -0.0232977  0.2253509  -0.103  0.91773    
## GOPC.l7  -0.0007967  0.0131223  -0.061  0.95163    
## GRA.l7    0.0402783  0.0875857   0.460  0.64596    
## RPO.l7    0.0495150  0.0766199   0.646  0.51864    
## USSR.l7  -0.4656210  0.2257143  -2.063  0.04003 *  
## GOPC.l8   0.0224316  0.0130031   1.725  0.08559 .  
## GRA.l8   -0.0716621  0.0875313  -0.819  0.41364    
## RPO.l8   -0.0216925  0.0767600  -0.283  0.77769    
## USSR.l8   0.0203852  0.2299260   0.089  0.92941    
## GOPC.l9   0.0018361  0.0129351   0.142  0.88722    
## GRA.l9   -0.0348409  0.0871237  -0.400  0.68953    
## RPO.l9   -0.0211776  0.0767949  -0.276  0.78293    
## USSR.l9  -0.0403153  0.2291235  -0.176  0.86045    
## GOPC.l10 -0.0128459  0.0126958  -1.012  0.31248    
## GRA.l10   0.0852814  0.0855656   0.997  0.31976    
## RPO.l10  -0.0733980  0.0761818  -0.963  0.33613    
## USSR.l10 -0.0467695  0.2273421  -0.206  0.83715    
## GOPC.l11  0.0100298  0.0126933   0.790  0.43009    
## GRA.l11   0.0775887  0.0843155   0.920  0.35823    
## RPO.l11   0.0711597  0.0767085   0.928  0.35436    
## USSR.l11  0.0436395  0.2254701   0.194  0.84667    
## GOPC.l12  0.0102755  0.0127592   0.805  0.42129    
## GRA.l12   0.0225023  0.0834686   0.270  0.78767    
## RPO.l12   0.0158919  0.0775205   0.205  0.83772    
## USSR.l12 -0.2018535  0.2235037  -0.903  0.36722    
## GOPC.l13 -0.0275151  0.0128350  -2.144  0.03290 *  
## GRA.l13  -0.1360462  0.0829271  -1.641  0.10199    
## RPO.l13   0.0076027  0.0764922   0.099  0.92090    
## USSR.l13 -0.0542324  0.2197629  -0.247  0.80526    
## GOPC.l14 -0.0068676  0.0128728  -0.533  0.59411    
## GRA.l14   0.0206803  0.0835594   0.247  0.80470    
## RPO.l14  -0.1325978  0.0752129  -1.763  0.07897 .  
## USSR.l14 -0.0654896  0.2439626  -0.268  0.78855    
## GOPC.l15  0.0126834  0.0129554   0.979  0.32840    
## GRA.l15  -0.1668676  0.0841908  -1.982  0.04843 *  
## RPO.l15   0.0552477  0.0766722   0.721  0.47176    
## USSR.l15  0.2288820  0.2456918   0.932  0.35234    
## GOPC.l16 -0.0237519  0.0131289  -1.809  0.07148 .  
## GRA.l16   0.1398646  0.0840069   1.665  0.09702 .  
## RPO.l16   0.0907591  0.0773111   1.174  0.24139    
## USSR.l16  0.2065186  0.2535976   0.814  0.41612    
## GOPC.l17  0.0015981  0.0128380   0.124  0.90102    
## GRA.l17   0.0492946  0.0842348   0.585  0.55887    
## RPO.l17  -0.0586692  0.0779978  -0.752  0.45256    
## USSR.l17  0.2564306  0.2548481   1.006  0.31517    
## GOPC.l18 -0.0010453  0.0125567  -0.083  0.93372    
## GRA.l18  -0.0272927  0.0843332  -0.324  0.74645    
## RPO.l18  -0.0661724  0.0778854  -0.850  0.39625    
## USSR.l18  0.1154986  0.2552852   0.452  0.65130    
## GOPC.l19 -0.0103724  0.0124981  -0.830  0.40728    
## GRA.l19   0.0258444  0.0842743   0.307  0.75932    
## RPO.l19   0.1199415  0.0783508   1.531  0.12692    
## USSR.l19 -0.1330073  0.2469641  -0.539  0.59060    
## GOPC.l20 -0.0067499  0.0123993  -0.544  0.58661    
## GRA.l20  -0.0174428  0.0859114  -0.203  0.83925    
## RPO.l20  -0.0903018  0.0786586  -1.148  0.25192    
## USSR.l20  0.0124956  0.2471007   0.051  0.95970    
## GOPC.l21  0.0061919  0.0122285   0.506  0.61300    
## GRA.l21  -0.1203291  0.0872211  -1.380  0.16879    
## RPO.l21  -0.0068561  0.0782342  -0.088  0.93023    
## USSR.l21  0.0099157  0.2419033   0.041  0.96733    
## GOPC.l22 -0.0158568  0.0118984  -1.333  0.18370    
## GRA.l22   0.1483100  0.0866785   1.711  0.08816 .  
## RPO.l22   0.1418314  0.0782461   1.813  0.07094 .  
## USSR.l22  0.2264569  0.2374343   0.954  0.34101    
## GOPC.l23 -0.0042543  0.0118937  -0.358  0.72084    
## GRA.l23   0.0844620  0.0869584   0.971  0.33222    
## RPO.l23  -0.1826180  0.0745134  -2.451  0.01485 *  
## USSR.l23  0.0561154  0.2356343   0.238  0.81194    
## GOPC.l24 -0.0118408  0.0118187  -1.002  0.31725    
## GRA.l24  -0.1276611  0.0570609  -2.237  0.02604 *  
## RPO.l24   0.0849188  0.0422406   2.010  0.04533 *  
## USSR.l24  0.1707592  0.2304690   0.741  0.45935    
## const    -0.2237883  0.2511122  -0.891  0.37358    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## 
## Residual standard error: 4.132 on 286 degrees of freedom
## Multiple R-Squared: 0.9648,  Adjusted R-squared: 0.9531 
## F-statistic: 81.78 on 96 and 286 DF,  p-value: < 2.2e-16 
## 
## 
## Estimation results for equation RPO: 
## ==================================== 
## RPO = GOPC.l1 + GRA.l1 + RPO.l1 + USSR.l1 + GOPC.l2 + GRA.l2 + RPO.l2 + USSR.l2 + GOPC.l3 + GRA.l3 + RPO.l3 + USSR.l3 + GOPC.l4 + GRA.l4 + RPO.l4 + USSR.l4 + GOPC.l5 + GRA.l5 + RPO.l5 + USSR.l5 + GOPC.l6 + GRA.l6 + RPO.l6 + USSR.l6 + GOPC.l7 + GRA.l7 + RPO.l7 + USSR.l7 + GOPC.l8 + GRA.l8 + RPO.l8 + USSR.l8 + GOPC.l9 + GRA.l9 + RPO.l9 + USSR.l9 + GOPC.l10 + GRA.l10 + RPO.l10 + USSR.l10 + GOPC.l11 + GRA.l11 + RPO.l11 + USSR.l11 + GOPC.l12 + GRA.l12 + RPO.l12 + USSR.l12 + GOPC.l13 + GRA.l13 + RPO.l13 + USSR.l13 + GOPC.l14 + GRA.l14 + RPO.l14 + USSR.l14 + GOPC.l15 + GRA.l15 + RPO.l15 + USSR.l15 + GOPC.l16 + GRA.l16 + RPO.l16 + USSR.l16 + GOPC.l17 + GRA.l17 + RPO.l17 + USSR.l17 + GOPC.l18 + GRA.l18 + RPO.l18 + USSR.l18 + GOPC.l19 + GRA.l19 + RPO.l19 + USSR.l19 + GOPC.l20 + GRA.l20 + RPO.l20 + USSR.l20 + GOPC.l21 + GRA.l21 + RPO.l21 + USSR.l21 + GOPC.l22 + GRA.l22 + RPO.l22 + USSR.l22 + GOPC.l23 + GRA.l23 + RPO.l23 + USSR.l23 + GOPC.l24 + GRA.l24 + RPO.l24 + USSR.l24 + const 
## 
##           Estimate Std. Error t value Pr(>|t|)    
## GOPC.l1   0.013168   0.018496   0.712   0.4771    
## GRA.l1    0.025183   0.084110   0.299   0.7648    
## RPO.l1    1.446905   0.059995  24.117  < 2e-16 ***
## USSR.l1  -0.164671   0.307562  -0.535   0.5928    
## GOPC.l2  -0.035818   0.018273  -1.960   0.0510 .  
## GRA.l2    0.004776   0.129023   0.037   0.9705    
## RPO.l2   -0.614867   0.103895  -5.918 9.29e-09 ***
## USSR.l2   0.794311   0.308377   2.576   0.0105 *  
## GOPC.l3   0.014033   0.018589   0.755   0.4509    
## GRA.l3   -0.099391   0.126769  -0.784   0.4337    
## RPO.l3    0.191247   0.110609   1.729   0.0849 .  
## USSR.l3   0.280047   0.311168   0.900   0.3689    
## GOPC.l4  -0.021326   0.019382  -1.100   0.2721    
## GRA.l4    0.178454   0.126039   1.416   0.1579    
## RPO.l4   -0.121700   0.110945  -1.097   0.2736    
## USSR.l4   0.321842   0.322182   0.999   0.3187    
## GOPC.l5  -0.006124   0.018852  -0.325   0.7455    
## GRA.l5   -0.135607   0.126523  -1.072   0.2847    
## RPO.l5    0.145922   0.109668   1.331   0.1844    
## USSR.l5  -0.283874   0.325152  -0.873   0.3834    
## GOPC.l6   0.013809   0.019280   0.716   0.4744    
## GRA.l6    0.043401   0.126715   0.343   0.7322    
## RPO.l6   -0.081927   0.109881  -0.746   0.4565    
## USSR.l6  -0.003877   0.325223  -0.012   0.9905    
## GOPC.l7  -0.006468   0.018938  -0.342   0.7330    
## GRA.l7    0.084087   0.126402   0.665   0.5064    
## RPO.l7    0.042328   0.110577   0.383   0.7022    
## USSR.l7   0.216880   0.325747   0.666   0.5061    
## GOPC.l8   0.007206   0.018766   0.384   0.7012    
## GRA.l8   -0.001024   0.126324  -0.008   0.9935    
## RPO.l8   -0.041952   0.110779  -0.379   0.7052    
## USSR.l8  -0.577344   0.331825  -1.740   0.0830 .  
## GOPC.l9   0.004317   0.018668   0.231   0.8173    
## GRA.l9    0.044031   0.125735   0.350   0.7265    
## RPO.l9   -0.046550   0.110829  -0.420   0.6748    
## USSR.l9  -0.242536   0.330667  -0.733   0.4639    
## GOPC.l10  0.004438   0.018322   0.242   0.8088    
## GRA.l10  -0.191926   0.123487  -1.554   0.1212    
## RPO.l10   0.150344   0.109944   1.367   0.1726    
## USSR.l10 -0.374854   0.328096  -1.143   0.2542    
## GOPC.l11  0.002111   0.018319   0.115   0.9084    
## GRA.l11   0.047066   0.121683   0.387   0.6992    
## RPO.l11  -0.077647   0.110704  -0.701   0.4836    
## USSR.l11 -0.006662   0.325395  -0.020   0.9837    
## GOPC.l12  0.018877   0.018414   1.025   0.3061    
## GRA.l12   0.123805   0.120460   1.028   0.3049    
## RPO.l12   0.005891   0.111876   0.053   0.9580    
## USSR.l12  0.178940   0.322557   0.555   0.5795    
## GOPC.l13 -0.002043   0.018523  -0.110   0.9122    
## GRA.l13  -0.163906   0.119679  -1.370   0.1719    
## RPO.l13  -0.188998   0.110392  -1.712   0.0880 .  
## USSR.l13  0.086661   0.317158   0.273   0.7849    
## GOPC.l14  0.015065   0.018578   0.811   0.4181    
## GRA.l14   0.008779   0.120592   0.073   0.9420    
## RPO.l14   0.256337   0.108546   2.362   0.0189 *  
## USSR.l14  0.652423   0.352083   1.853   0.0649 .  
## GOPC.l15 -0.023287   0.018697  -1.246   0.2140    
## GRA.l15   0.025691   0.121503   0.211   0.8327    
## RPO.l15  -0.213459   0.110652  -1.929   0.0547 .  
## USSR.l15  0.343139   0.354578   0.968   0.3340    
## GOPC.l16 -0.006323   0.018947  -0.334   0.7389    
## GRA.l16   0.017935   0.121237   0.148   0.8825    
## RPO.l16   0.120134   0.111574   1.077   0.2825    
## USSR.l16  0.706772   0.365988   1.931   0.0545 .  
## GOPC.l17  0.014386   0.018528   0.776   0.4381    
## GRA.l17   0.133044   0.121566   1.094   0.2747    
## RPO.l17   0.027161   0.112565   0.241   0.8095    
## USSR.l17  0.113747   0.367793   0.309   0.7573    
## GOPC.l18  0.008680   0.018122   0.479   0.6323    
## GRA.l18  -0.162792   0.121708  -1.338   0.1821    
## RPO.l18  -0.044219   0.112403  -0.393   0.6943    
## USSR.l18 -0.468301   0.368423  -1.271   0.2047    
## GOPC.l19 -0.009808   0.018037  -0.544   0.5870    
## GRA.l19  -0.018852   0.121623  -0.155   0.8769    
## RPO.l19   0.045769   0.113075   0.405   0.6860    
## USSR.l19 -0.033714   0.356414  -0.095   0.9247    
## GOPC.l20 -0.013552   0.017894  -0.757   0.4495    
## GRA.l20   0.233269   0.123986   1.881   0.0609 .  
## RPO.l20   0.058540   0.113519   0.516   0.6065    
## USSR.l20 -0.127005   0.356612  -0.356   0.7220    
## GOPC.l21  0.017444   0.017648   0.988   0.3238    
## GRA.l21  -0.217676   0.125876  -1.729   0.0848 .  
## RPO.l21  -0.122334   0.112906  -1.083   0.2795    
## USSR.l21 -0.461896   0.349111  -1.323   0.1869    
## GOPC.l22  0.014065   0.017172   0.819   0.4134    
## GRA.l22   0.163648   0.125093   1.308   0.1919    
## RPO.l22   0.130040   0.112924   1.152   0.2505    
## USSR.l22 -0.246169   0.342661  -0.718   0.4731    
## GOPC.l23  0.011246   0.017165   0.655   0.5129    
## GRA.l23  -0.074353   0.125497  -0.592   0.5540    
## RPO.l23  -0.173853   0.107537  -1.617   0.1070    
## USSR.l23 -0.380674   0.340064  -1.119   0.2639    
## GOPC.l24 -0.007196   0.017057  -0.422   0.6734    
## GRA.l24  -0.015966   0.082349  -0.194   0.8464    
## RPO.l24   0.093254   0.060961   1.530   0.1272    
## USSR.l24  0.265824   0.332609   0.799   0.4248    
## const     0.046228   0.362401   0.128   0.8986    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## 
## Residual standard error: 5.963 on 286 degrees of freedom
## Multiple R-Squared: 0.9872,  Adjusted R-squared: 0.9829 
## F-statistic: 229.7 on 96 and 286 DF,  p-value: < 2.2e-16 
## 
## 
## Estimation results for equation USSR: 
## ===================================== 
## USSR = GOPC.l1 + GRA.l1 + RPO.l1 + USSR.l1 + GOPC.l2 + GRA.l2 + RPO.l2 + USSR.l2 + GOPC.l3 + GRA.l3 + RPO.l3 + USSR.l3 + GOPC.l4 + GRA.l4 + RPO.l4 + USSR.l4 + GOPC.l5 + GRA.l5 + RPO.l5 + USSR.l5 + GOPC.l6 + GRA.l6 + RPO.l6 + USSR.l6 + GOPC.l7 + GRA.l7 + RPO.l7 + USSR.l7 + GOPC.l8 + GRA.l8 + RPO.l8 + USSR.l8 + GOPC.l9 + GRA.l9 + RPO.l9 + USSR.l9 + GOPC.l10 + GRA.l10 + RPO.l10 + USSR.l10 + GOPC.l11 + GRA.l11 + RPO.l11 + USSR.l11 + GOPC.l12 + GRA.l12 + RPO.l12 + USSR.l12 + GOPC.l13 + GRA.l13 + RPO.l13 + USSR.l13 + GOPC.l14 + GRA.l14 + RPO.l14 + USSR.l14 + GOPC.l15 + GRA.l15 + RPO.l15 + USSR.l15 + GOPC.l16 + GRA.l16 + RPO.l16 + USSR.l16 + GOPC.l17 + GRA.l17 + RPO.l17 + USSR.l17 + GOPC.l18 + GRA.l18 + RPO.l18 + USSR.l18 + GOPC.l19 + GRA.l19 + RPO.l19 + USSR.l19 + GOPC.l20 + GRA.l20 + RPO.l20 + USSR.l20 + GOPC.l21 + GRA.l21 + RPO.l21 + USSR.l21 + GOPC.l22 + GRA.l22 + RPO.l22 + USSR.l22 + GOPC.l23 + GRA.l23 + RPO.l23 + USSR.l23 + GOPC.l24 + GRA.l24 + RPO.l24 + USSR.l24 + const 
## 
##            Estimate Std. Error t value Pr(>|t|)    
## GOPC.l1   0.0029064  0.0034096   0.852 0.394708    
## GRA.l1    0.0140124  0.0155055   0.904 0.366913    
## RPO.l1   -0.0135327  0.0110599  -1.224 0.222116    
## USSR.l1  -0.0581940  0.0566981  -1.026 0.305578    
## GOPC.l2   0.0028392  0.0033686   0.843 0.400029    
## GRA.l2   -0.0025951  0.0237851  -0.109 0.913195    
## RPO.l2    0.0101092  0.0191527   0.528 0.598034    
## USSR.l2  -0.1416585  0.0568484  -2.492 0.013274 *  
## GOPC.l3   0.0040800  0.0034269   1.191 0.234801    
## GRA.l3   -0.0185202  0.0233695  -0.792 0.428730    
## RPO.l3   -0.0053587  0.0203904  -0.263 0.792890    
## USSR.l3   0.2581135  0.0573629   4.500 9.91e-06 ***
## GOPC.l4  -0.0010391  0.0035731  -0.291 0.771411    
## GRA.l4    0.0593446  0.0232350   2.554 0.011165 *  
## RPO.l4    0.0086409  0.0204524   0.422 0.672986    
## USSR.l4   0.0500138  0.0593934   0.842 0.400449    
## GOPC.l5   0.0052622  0.0034754   1.514 0.131097    
## GRA.l5   -0.0521731  0.0233241  -2.237 0.026065 *  
## RPO.l5   -0.0198651  0.0202171  -0.983 0.326639    
## USSR.l5   0.0796988  0.0599409   1.330 0.184702    
## GOPC.l6   0.0015711  0.0035542   0.442 0.658792    
## GRA.l6    0.0023891  0.0233595   0.102 0.918610    
## RPO.l6    0.0372354  0.0202562   1.838 0.067067 .  
## USSR.l6   0.1814172  0.0599539   3.026 0.002704 ** 
## GOPC.l7   0.0002589  0.0034912   0.074 0.940932    
## GRA.l7   -0.0122479  0.0233019  -0.526 0.599562    
## RPO.l7   -0.0368360  0.0203845  -1.807 0.071803 .  
## USSR.l7   0.0196915  0.0600506   0.328 0.743216    
## GOPC.l8   0.0048125  0.0034594   1.391 0.165273    
## GRA.l8    0.0437877  0.0232874   1.880 0.061081 .  
## RPO.l8    0.0291006  0.0204217   1.425 0.155253    
## USSR.l8   0.1149466  0.0611711   1.879 0.061248 .  
## GOPC.l9   0.0039472  0.0034413   1.147 0.252344    
## GRA.l9   -0.0254723  0.0231790  -1.099 0.272719    
## RPO.l9   -0.0336992  0.0204310  -1.649 0.100162    
## USSR.l9   0.0336916  0.0609576   0.553 0.580897    
## GOPC.l10  0.0016361  0.0033777   0.484 0.628489    
## GRA.l10   0.0148370  0.0227645   0.652 0.515077    
## RPO.l10   0.0158265  0.0202679   0.781 0.435529    
## USSR.l10 -0.0321164  0.0604836  -0.531 0.595836    
## GOPC.l11  0.0039906  0.0033770   1.182 0.238306    
## GRA.l11   0.0109818  0.0224319   0.490 0.624818    
## RPO.l11   0.0104069  0.0204081   0.510 0.610487    
## USSR.l11  0.0187873  0.0599856   0.313 0.754359    
## GOPC.l12  0.0004390  0.0033945   0.129 0.897202    
## GRA.l12  -0.0452638  0.0222065  -2.038 0.042439 *  
## RPO.l12  -0.0356935  0.0206241  -1.731 0.084589 .  
## USSR.l12 -0.5208241  0.0594625  -8.759  < 2e-16 ***
## GOPC.l13  0.0027315  0.0034147   0.800 0.424422    
## GRA.l13   0.0548078  0.0220625   2.484 0.013556 *  
## RPO.l13   0.0614710  0.0203505   3.021 0.002751 ** 
## USSR.l13 -0.0529849  0.0584672  -0.906 0.365576    
## GOPC.l14  0.0059040  0.0034248   1.724 0.085805 .  
## GRA.l14  -0.0411000  0.0222307  -1.849 0.065520 .  
## RPO.l14  -0.0759633  0.0200102  -3.796 0.000179 ***
## USSR.l14 -0.0423042  0.0649055  -0.652 0.515066    
## GOPC.l15  0.0095867  0.0034467   2.781 0.005773 ** 
## GRA.l15   0.0035112  0.0223987   0.157 0.875545    
## RPO.l15   0.0813139  0.0203984   3.986 8.53e-05 ***
## USSR.l15  0.2292846  0.0653655   3.508 0.000525 ***
## GOPC.l16 -0.0006768  0.0034929  -0.194 0.846496    
## GRA.l16  -0.0076873  0.0223498  -0.344 0.731133    
## RPO.l16  -0.0672092  0.0205684  -3.268 0.001217 ** 
## USSR.l16  0.1216073  0.0674688   1.802 0.072532 .  
## GOPC.l17  0.0009340  0.0034155   0.273 0.784707    
## GRA.l17   0.0317834  0.0224104   1.418 0.157208    
## RPO.l17   0.0407566  0.0207511   1.964 0.050490 .  
## USSR.l17  0.1183042  0.0678015   1.745 0.082083 .  
## GOPC.l18  0.0049041  0.0033407   1.468 0.143201    
## GRA.l18  -0.0118184  0.0224366  -0.527 0.598778    
## RPO.l18  -0.0147280  0.0207212  -0.711 0.477806    
## USSR.l18  0.1852271  0.0679178   2.727 0.006782 ** 
## GOPC.l19 -0.0026958  0.0033251  -0.811 0.418193    
## GRA.l19   0.0052265  0.0224209   0.233 0.815845    
## RPO.l19   0.0025540  0.0208450   0.123 0.902569    
## USSR.l19  0.0110614  0.0657040   0.168 0.866426    
## GOPC.l20  0.0012596  0.0032988   0.382 0.702873    
## GRA.l20  -0.0046347  0.0228565  -0.203 0.839455    
## RPO.l20  -0.0090478  0.0209269  -0.432 0.665810    
## USSR.l20  0.0314814  0.0657404   0.479 0.632394    
## GOPC.l21  0.0038619  0.0032534   1.187 0.236193    
## GRA.l21  -0.0148647  0.0232049  -0.641 0.522307    
## RPO.l21  -0.0006461  0.0208140  -0.031 0.975258    
## USSR.l21  0.0172383  0.0643576   0.268 0.789007    
## GOPC.l22  0.0008933  0.0031655   0.282 0.777995    
## GRA.l22   0.0013801  0.0230605   0.060 0.952320    
## RPO.l22   0.0353943  0.0208171   1.700 0.090172 .  
## USSR.l22 -0.1132701  0.0631686  -1.793 0.074007 .  
## GOPC.l23 -0.0044274  0.0031643  -1.399 0.162849    
## GRA.l23  -0.0029853  0.0231350  -0.129 0.897418    
## RPO.l23  -0.0285322  0.0198241  -1.439 0.151167    
## USSR.l23 -0.0127512  0.0626898  -0.203 0.838965    
## GOPC.l24  0.0045899  0.0031443   1.460 0.145457    
## GRA.l24   0.0138337  0.0151809   0.911 0.362924    
## RPO.l24   0.0084847  0.0112380   0.755 0.450870    
## USSR.l24 -0.3295174  0.0613155  -5.374 1.60e-07 ***
## const     0.1363407  0.0668076   2.041 0.042189 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## 
## Residual standard error: 1.099 on 286 degrees of freedom
## Multiple R-Squared: 0.4757,  Adjusted R-squared: 0.2997 
## F-statistic: 2.703 on 96 and 286 DF,  p-value: 8.175e-11 
## 
## 
## 
## Covariance matrix of residuals:
##          GOPC     GRA      RPO    USSR
## GOPC 357.6018 -0.4482 -11.6081 -0.9295
## GRA   -0.4482 17.0705   1.8063  0.1848
## RPO  -11.6081  1.8063  35.5542 -0.7962
## USSR  -0.9295  0.1848  -0.7962  1.2083
## 
## Correlation matrix of residuals:
##           GOPC       GRA      RPO     USSR
## GOPC  1.000000 -0.005737 -0.10295 -0.04472
## GRA  -0.005737  1.000000  0.07332  0.04070
## RPO  -0.102947  0.073319  1.00000 -0.12148
## USSR -0.044716  0.040701 -0.12148  1.00000
```

\item Using the estimated VAR, compute impulse response functions (take a look at the irf() function in vars, it uses the same identification scheme as Kilian and Park (2009) propose (recursive ordering based on a Cholesky decomposition of the vcov-matrix of the errors) by default. Replicate Figure 1 and the lower panel in figure 3 of Kilian and Park (2009). Interpret the results.

```r
ir.mod1 <- irf(mod1, impulse=c("GOPC","GRA","RPO"), response = "RPO",n.ahead = 15)

# Reverse GOPC
for(i in 1:length(ir.mod1$irf$GOPC)){
  ir.mod1$irf$GOPC[i] <- ir.mod1$irf$GOPC[i]*(-1)
  ir.mod1$Upper$GOPC[i] <- ir.mod1$Upper$GOPC[i]*(-1)
  ir.mod1$Lower$GOPC[i] <- ir.mod1$Lower$GOPC[i]*(-1)
}

plot(ir.mod1,ylim=c(-6,12))
```

![](Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-8-1.pdf)<!-- --> ![](Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-8-2.pdf)<!-- --> ![](Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-8-3.pdf)<!-- --> 

```r
########################NOT WORKING FROM HERE ON########################

ir.mod1_cumulative <- irf(mod1,impulse="GOPC",response = "RPO",n.ahead = 15, cumulative = TRUE)
# Reverse GOPC
for(i in 1:length(ir.mod1_cumulative$irf$GOPC)){
  ir.mod1_cumulative$irf$GOPC[i] <- ir.mod1_cumulative$irf$GOPC[i]*(-1)
  ir.mod1_cumulative$Upper$GOPC[i] <- ir.mod1_cumulative$Upper$GOPC[i]*(-1)
  ir.mod1_cumulative$Lower$GOPC[i] <- ir.mod1_cumulative$Lower$GOPC[i]*(-1)
}

plot(ir.mod1_cumulative)
```

![](Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-8-4.pdf)<!-- --> 

\item Calculate forecast error variance decompositions for the included variables (take a look at the fevd() function in vars). Replicate Table 2 of Kilian and Park (2009). Interpret the results.


```r
fevd_mod1 <- vars::fevd(mod1, n.ahead=12)
table2 <- round(fevd_mod1$USSR[c(1,2,3,12),]*100,2)
table2
```

```
##      GOPC  GRA  RPO  USSR
## [1,] 0.20 0.16 1.69 97.94
## [2,] 0.55 0.36 2.09 97.00
## [3,] 0.76 0.48 2.12 96.64
## [4,] 2.80 6.83 4.53 85.84
```

\item Note that the dataset provided misses US stock market returns (due to the licensing of the underlying time series). Look for alternative data on the US stock market, create a variable similar to the one used by Kilian and Park (2009). Re-estimate the model and replicate Figure 1 again as well as the top panel of Figure 3 and Table 1.5 Interpret the results.

```r
options(scipen=5)
fred <- read.csv("FRED_MD_data.csv")[,c("sasdate","S.P.500","CPIAUCSL")][-1,]
str(fred)
```

```
## 'data.frame':    770 obs. of  3 variables:
##  $ sasdate : chr  "1/1/1959" "2/1/1959" "3/1/1959" "4/1/1959" ...
##  $ S.P.500 : num  55.6 54.8 56.2 57.1 58 ...
##  $ CPIAUCSL: num  29 29 29 29 29 ...
```

```r
# Extract SP500 Growth and Inflation
ret <- input_function(fred$S.P.500)$mom_growth
inf <- input_function(fred$CPIAUCSL)$mom_growth

# Compute deflated stock returns
stockret <- ret - inf
head(stockret)
```

```
## [1]        NA -1.493756  2.641334  1.639271  1.299090 -1.103711
```

```r
# Create time series
stockret_ts <- ts(stockret, frequency=12, start=c(1959,1))
head(stockret_ts)
```

```
##            Jan       Feb       Mar       Apr       May       Jun
## 1959        NA -1.493756  2.641334  1.639271  1.299090 -1.103711
```

```r
plot(stockret_ts)
```

![](Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-10-1.pdf)<!-- --> 

```r
stockret_ts <- window(stockret_ts, start=c(1973,1), end=c(2016,12))
plot(stockret_ts)
```

![](Assignment1_Macrotrics_files/figure-latex/unnamed-chunk-10-2.pdf)<!-- --> 

```r
# Create new data set
# data_new <- cbind(data,as.numeric(stockret_ts))
```
\end{itemize}

\end{document}
